# Generated by Django 4.2.23 on 2025-08-20 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active (soft delete mechanism)')),
                ('event_type', models.CharField(choices=[('api_call', 'API Call'), ('download', 'Download'), ('view', 'View')], help_text='Type of usage event', max_length=20)),
                ('endpoint', models.CharField(help_text='Specific API endpoint or URL that was accessed', max_length=500)),
                ('request_size', models.PositiveIntegerField(default=0, help_text='Size of the request in bytes')),
                ('response_size', models.PositiveIntegerField(default=0, help_text='Size of the response in bytes')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the client making the request')),
                ('user_agent', models.TextField(help_text='User agent string from the client')),
                ('metadata', models.JSONField(default=dict, help_text='Additional event-specific metadata and tracking data')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the event occurred')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in the database')),
                ('distribution', models.ForeignKey(help_text='Specific distribution that was used', on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='content.distribution')),
                ('resource', models.ForeignKey(help_text='Resource that was accessed', on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='content.resource')),
                ('user', models.ForeignKey(help_text='User who triggered the event', on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage Event',
                'verbose_name_plural': 'Usage Events',
                'db_table': 'usage_event',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['user'], name='usage_event_user_id_a72ba7_idx'), models.Index(fields=['resource'], name='usage_event_resourc_645921_idx'), models.Index(fields=['distribution'], name='usage_event_distrib_802973_idx'), models.Index(fields=['event_type'], name='usage_event_event_t_60aa57_idx'), models.Index(fields=['occurred_at'], name='usage_event_occurre_7ec242_idx'), models.Index(fields=['ip_address'], name='usage_event_ip_addr_8cb190_idx'), models.Index(fields=['user', 'occurred_at'], name='usage_event_user_id_39ce67_idx'), models.Index(fields=['resource', 'occurred_at'], name='usage_event_resourc_27c490_idx'), models.Index(fields=['event_type', 'occurred_at'], name='usage_event_event_t_2e51f1_idx')],
            },
        ),
    ]
