# Generated by Django 5.2.14 on 2026-10-05 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0069_assetlanguage_published_version'),
        ('simple_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalassetlanguage',
            name='published_version',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The version consumers are served for this language (translations / tafsirs). Set only by publishing a fully approved version; empty means nothing is visible.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='content.assetversion'),
        ),
        migrations.AlterField(
            model_name='historicalassetlanguage',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready')], default='draft', help_text="Consumer availability of this language rendition. DRAFT hides it from consumers (a translation in progress, or a source the publisher hid); READY makes it downloadable. The source language is created READY. The asset's own Asset.status remains the overarching gate.", max_length=20),
        ),
    ]
