# Generated by Django 5.2.14 on 2026-10-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_history', '0003_historicalassetversion_label_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalDistribution',
        ),
    ]
