# Generated by Django 5.2.14 on 2026-10-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_history', '0004_delete_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalassetversion',
            name='label_ar',
            field=models.CharField(blank=True, default='', help_text='Human-readable version name (tafsirs and translations); translated to en/ar.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalassetversion',
            name='label_en',
            field=models.CharField(blank=True, default='', help_text='Human-readable version name (tafsirs and translations); translated to en/ar.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalassetversion',
            name='summary_ar',
            field=models.TextField(blank=True, help_text='Asset version summary; translated to en/ar.', null=True),
        ),
        migrations.AddField(
            model_name='historicalassetversion',
            name='summary_en',
            field=models.TextField(blank=True, help_text='Asset version summary; translated to en/ar.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalassetversion',
            name='label',
            field=models.CharField(blank=True, default='', help_text='Human-readable version name (tafsirs and translations); translated to en/ar.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalassetversion',
            name='summary',
            field=models.TextField(blank=True, help_text='Asset version summary; translated to en/ar.'),
        ),
    ]
