# Generated by Django 4.2.23 on 2025-08-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("licensing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="notification_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether notification email has been sent for status change",
            ),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low Priority"),
                    ("normal", "Normal Priority"),
                    ("high", "High Priority"),
                    ("urgent", "Urgent"),
                ],
                default="normal",
                help_text="Request priority level",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="rejection_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("insufficient_justification", "Insufficient Justification"),
                    ("license_violation", "License Terms Violation"),
                    ("incomplete_information", "Incomplete Information"),
                    ("policy_violation", "Policy Violation"),
                    ("resource_unavailable", "Resource Unavailable"),
                    ("other", "Other"),
                ],
                help_text="Reason for rejection if applicable",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="terms_ar",
            field=models.TextField(
                help_text="Legal terms and conditions for using the resource", null=True
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="terms_en",
            field=models.TextField(
                help_text="Legal terms and conditions for using the resource", null=True
            ),
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                    ("revoked", "Revoked"),
                ],
                default="pending",
                help_text="Current status of the access request",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="accessrequest",
            index=models.Index(
                fields=["priority"], name="access_requ_priorit_4740b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessrequest",
            index=models.Index(
                fields=["notification_sent"], name="access_requ_notific_0d23f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessrequest",
            index=models.Index(
                fields=["status", "requested_at"], name="access_requ_status_baf326_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accessrequest",
            index=models.Index(
                fields=["priority", "requested_at"],
                name="access_requ_priorit_e6c670_idx",
            ),
        ),
    ]
