# Generated by Django 5.2.6 on 2025-10-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publishers", "0002_alter_publisher_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="description_ar",
            field=models.TextField(
                blank=True, help_text="Detailed publisher description", null=True
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="description_en",
            field=models.TextField(
                blank=True, help_text="Detailed publisher description", null=True
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="name_ar",
            field=models.CharField(
                help_text="Publisher name e.g. 'Tafsir Center'",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="name_en",
            field=models.CharField(
                help_text="Publisher name e.g. 'Tafsir Center'",
                max_length=255,
                null=True,
            ),
        ),
    ]
