# Generated by Django 5.2.6 on 2025-11-11 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("publishers", "0003_publisher_description_ar_publisher_description_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publisher",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="publishermember",
            name="is_active",
        ),
    ]
