# Generated by Django 5.2.6 on 2025-12-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publishers", "0005_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publisher",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, help_text="URL-friendly slug e.g. 'tafsir-center'", unique=True
            ),
        ),
    ]
