# Generated by Django 5.2.11 on 2026-03-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publishers", "0006_alter_publisher_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="country",
            field=models.CharField(blank=True, help_text="Country of the publisher", max_length=100),
        ),
        migrations.AddField(
            model_name="publisher",
            name="foundation_year",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Year the publisher was established", null=True
            ),
        ),
    ]
