# Generated by Django 5.2.14 on 2026-06-15 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def activate_members_and_remap_legacy_roles(apps, schema_editor):
    PublisherMember = apps.get_model("publishers", "PublisherMember")
    PublisherMember.objects.filter(role="owner").update(role="admin")
    PublisherMember.objects.filter(role="manager").update(role="staff")
    PublisherMember.objects.update(status="active")


def restore_legacy_member_roles_and_status(apps, schema_editor):
    PublisherMember = apps.get_model("publishers", "PublisherMember")
    PublisherMember.objects.filter(role="admin").update(role="owner")
    PublisherMember.objects.filter(role="staff").update(role="manager")
    PublisherMember.objects.update(status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0009_reslug_with_english_based_logic'),
        ('plain_permissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publishermember',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='pending', help_text='PENDING until the member accepts their invitation; ACTIVE after acceptance.', max_length=20),
        ),
        migrations.AlterField(
            model_name='publishermember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], help_text='Role label for this member. Drives permission group assignment on activation; has no effect on runtime authorization.', max_length=20),
        ),
        migrations.RunPython(
            activate_members_and_remap_legacy_roles,
            restore_legacy_member_roles_and_status,
        ),
        migrations.CreateModel(
            name='PublisherMemberInvitation',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('token_hash', models.CharField(help_text='sha256 of the raw token; raw token only in email.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_member_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_member_invitations', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='publishers.publishermember')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_invitations', to='publishers.publisher')),
            ],
            options={
                'indexes': [models.Index(fields=['token_hash'], name='publishers__token_h_0c2875_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('member',), name='uniq_pending_invite_per_member')],
            },
        ),
    ]
