# Generated by Django 5.2.14 on 2026-06-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0010_publisher_member_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishermemberinvitation',
            name='token_hash',
            field=models.CharField(blank=True, help_text='sha256 of the raw token; raw token only in email. Cleared (NULL) once the invitation is consumed.', max_length=64, null=True, unique=True),
        ),
    ]
