# Generated by Django 5.2.14 on 2026-06-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0011_alter_publishermemberinvitation_token_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='auto_accept_access_requests',
            field=models.BooleanField(default=True, help_text="When true, new asset access requests for this publisher's assets are granted automatically."),
        ),
    ]
