# Generated by Django 5.2.14 on 2026-09-15 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0013_publishermember_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLanguage',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('language', models.CharField(help_text="Language code the member works in, e.g. 'fr'", max_length=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='publishers.publishermember')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('member', 'language'), name='unique_member_language')],
            },
        ),
    ]
