# Generated by Django 4.2.23 on 2025-08-21 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0002_resource_description_ar_resource_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="review_notes",
            field=models.TextField(
                blank=True, help_text="Notes from the reviewer about the resource"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the resource was reviewed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who reviewed this resource (must have Reviewer role)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_resources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="submitted_for_review_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when resource was submitted for review",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="workflow_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_review", "In Review"),
                    ("reviewed", "Reviewed"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                help_text="Current workflow status of the resource",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["workflow_status"], name="resource_workflo_e9a03f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["reviewed_by"], name="resource_reviewe_5b996e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["submitted_for_review_at"], name="resource_submitt_4c81be_idx"
            ),
        ),
    ]
