# Generated by Django 5.2.6 on 2025-09-17 14:49

import apps.core.uploads
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("publishers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete mechanism)",
                    ),
                ),
                ("name", models.CharField(help_text="Asset name", max_length=255)),
                (
                    "name_en",
                    models.CharField(help_text="Asset name", max_length=255, null=True),
                ),
                (
                    "name_ar",
                    models.CharField(help_text="Asset name", max_length=255, null=True),
                ),
                ("description", models.TextField(help_text="Asset description")),
                (
                    "description_en",
                    models.TextField(help_text="Asset description", null=True),
                ),
                (
                    "description_ar",
                    models.TextField(help_text="Asset description", null=True),
                ),
                (
                    "long_description",
                    models.TextField(blank=True, help_text="Extended description"),
                ),
                (
                    "long_description_en",
                    models.TextField(
                        blank=True, help_text="Extended description", null=True
                    ),
                ),
                (
                    "long_description_ar",
                    models.TextField(
                        blank=True, help_text="Extended description", null=True
                    ),
                ),
                (
                    "thumbnail_url",
                    models.ImageField(
                        blank=True,
                        help_text="Asset thumbnail image",
                        upload_to=apps.core.uploads.upload_to_asset_thumbnails,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"]
                            )
                        ],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("recitation", "Recitation"),
                            ("mushaf", "Mushaf"),
                            ("tafsir", "Tafsir"),
                        ],
                        help_text="Asset category matching resource categories",
                        max_length=20,
                    ),
                ),
                (
                    "license",
                    models.CharField(
                        choices=[
                            ("CC0", "Creative Commons Zero"),
                            ("CC BY", "Creative Commons Attribution"),
                            ("CC BY-SA", "Creative Commons Attribution-ShareAlike"),
                            ("CC BY-ND", "Creative Commons Attribution-NoDerivs"),
                            ("CC BY-NC", "Creative Commons Attribution-NonCommercial"),
                            (
                                "CC BY-NC-SA",
                                "Creative Commons Attribution-NonCommercial-ShareAlike",
                            ),
                            (
                                "CC BY-NC-ND",
                                "Creative Commons Attribution-NonCommercial-NoDerivs",
                            ),
                            ("Public Domain", "Public Domain"),
                            ("Proprietary", "Proprietary"),
                        ],
                        help_text="Asset license",
                        max_length=50,
                    ),
                ),
                (
                    "file_size",
                    models.CharField(
                        help_text="Human readable file size e.g. '2.5 MB'",
                        max_length=50,
                    ),
                ),
                ("format", models.CharField(help_text="File format", max_length=50)),
                (
                    "encoding",
                    models.CharField(
                        default="UTF-8", help_text="Text encoding", max_length=50
                    ),
                ),
                ("version", models.CharField(help_text="Asset version", max_length=50)),
                (
                    "language",
                    models.CharField(help_text="Asset language code", max_length=10),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssetAccessRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete mechanism)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "developer_access_reason",
                    models.TextField(
                        help_text="Reason for requesting access - used in V1 UI"
                    ),
                ),
                (
                    "intended_use",
                    models.CharField(
                        choices=[
                            ("commercial", "Commercial"),
                            ("non-commercial", "Non-Commercial"),
                        ],
                        help_text="Commercial or non-commercial use",
                        max_length=20,
                    ),
                ),
                (
                    "admin_response",
                    models.TextField(blank=True, help_text="Admin response message"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="When request was approved", null=True
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_asset_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_requests",
                        to="content.asset",
                    ),
                ),
                (
                    "developer_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssetPreview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete mechanism)",
                    ),
                ),
                (
                    "image_url",
                    models.ImageField(
                        blank=True,
                        help_text="Preview image",
                        upload_to=apps.core.uploads.upload_to_asset_preview_images,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"]
                            )
                        ],
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, help_text="Display order"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previews",
                        to="content.asset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete mechanism)",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Resource name e.g. 'Tafsir Ibn Katheer CSV'",
                        max_length=255,
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Resource name e.g. 'Tafsir Ibn Katheer CSV'",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        help_text="Resource name e.g. 'Tafsir Ibn Katheer CSV'",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL slug e.g. 'tafsir-ibn-katheer-csv'"
                    ),
                ),
                ("description", models.TextField(help_text="Resource description")),
                (
                    "description_en",
                    models.TextField(help_text="Resource description", null=True),
                ),
                (
                    "description_ar",
                    models.TextField(help_text="Resource description", null=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("recitation", "Recitation"),
                            ("mushaf", "Mushaf"),
                            ("tafsir", "Tafsir"),
                        ],
                        help_text="Simple options in V1",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("ready", "Ready")],
                        default="draft",
                        help_text="V1: ready = ready to extract Assets from",
                        max_length=20,
                    ),
                ),
                (
                    "license",
                    models.CharField(
                        choices=[
                            ("CC0", "Creative Commons Zero"),
                            ("CC BY", "Creative Commons Attribution"),
                            ("CC BY-SA", "Creative Commons Attribution-ShareAlike"),
                            ("CC BY-ND", "Creative Commons Attribution-NoDerivs"),
                            ("CC BY-NC", "Creative Commons Attribution-NonCommercial"),
                            (
                                "CC BY-NC-SA",
                                "Creative Commons Attribution-NonCommercial-ShareAlike",
                            ),
                            (
                                "CC BY-NC-ND",
                                "Creative Commons Attribution-NonCommercial-NoDerivs",
                            ),
                            ("Public Domain", "Public Domain"),
                            ("Proprietary", "Proprietary"),
                        ],
                        default="CC0",
                        help_text="Asset license",
                        max_length=50,
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="publishers.publisher",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="content.resource",
            ),
        ),
        migrations.CreateModel(
            name="ResourceVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete mechanism)",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Version name - V1: same as resource name, V2: updates on content",
                        max_length=255,
                    ),
                ),
                ("summary", models.TextField(blank=True, help_text="Version summary")),
                (
                    "semvar",
                    models.CharField(
                        help_text="Semantic versioning e.g. '1.0.0' - core to bind with an AssetVersion",
                        max_length=20,
                    ),
                ),
                (
                    "storage_url",
                    models.FileField(
                        help_text="File storage for resource version",
                        upload_to=apps.core.uploads.upload_to_resource_files,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "txt",
                                    "zip",
                                    "tar",
                                    "gz",
                                    "json",
                                    "xml",
                                    "csv",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("excel", "Excel"),
                            ("json", "JSON"),
                            ("zip", "ZIP"),
                        ],
                        help_text="File type",
                        max_length=20,
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(
                        default=0, help_text="File size in bytes"
                    ),
                ),
                (
                    "is_latest",
                    models.BooleanField(
                        default=False, help_text="Whether this is the latest version"
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="content.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Version",
                "verbose_name_plural": "Resource Versions",
                "unique_together": {("resource", "semvar")},
            },
        ),
        migrations.CreateModel(
            name="AssetVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete mechanism)",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Asset version name", max_length=255),
                ),
                (
                    "summary",
                    models.TextField(blank=True, help_text="Asset version summary"),
                ),
                (
                    "file_url",
                    models.FileField(
                        blank=True,
                        help_text="Direct file for asset",
                        null=True,
                        upload_to=apps.core.uploads.upload_to_asset_files,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "txt",
                                    "zip",
                                    "tar",
                                    "gz",
                                    "json",
                                    "xml",
                                    "csv",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(help_text="File size in bytes"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="content.asset",
                    ),
                ),
                (
                    "resource_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_versions",
                        to="content.resourceversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssetAccess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "effective_license",
                    models.CharField(
                        choices=[
                            ("CC0", "Creative Commons Zero"),
                            ("CC BY", "Creative Commons Attribution"),
                            ("CC BY-SA", "Creative Commons Attribution-ShareAlike"),
                            ("CC BY-ND", "Creative Commons Attribution-NoDerivs"),
                            ("CC BY-NC", "Creative Commons Attribution-NonCommercial"),
                            (
                                "CC BY-NC-SA",
                                "Creative Commons Attribution-NonCommercial-ShareAlike",
                            ),
                            (
                                "CC BY-NC-ND",
                                "Creative Commons Attribution-NonCommercial-NoDerivs",
                            ),
                            ("Public Domain", "Public Domain"),
                            ("Proprietary", "Proprietary"),
                        ],
                        help_text="Access license at time of grant",
                        max_length=50,
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When access was granted"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When access expires (null = never expires)",
                        null=True,
                    ),
                ),
                (
                    "download_url",
                    models.URLField(
                        blank=True,
                        help_text="Direct download URL, can contain signed URL if needed",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_accesses",
                        to="content.asset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset_access_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_grant",
                        to="content.assetaccessrequest",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "asset")},
            },
        ),
        migrations.CreateModel(
            name="Distribution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete mechanism)",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("REST_JSON", "REST API (JSON)"),
                            ("GraphQL", "GraphQL API"),
                            ("ZIP", "ZIP Download"),
                            ("API", "Custom API"),
                        ],
                        help_text="Format/method for accessing the asset",
                        max_length=20,
                    ),
                ),
                (
                    "asset_version",
                    models.ForeignKey(
                        help_text="Asset that this distribution provides access to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to="content.assetversion",
                    ),
                ),
            ],
            options={
                "unique_together": {("asset_version", "channel")},
            },
        ),
        migrations.CreateModel(
            name="UsageEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete mechanism)",
                    ),
                ),
                (
                    "usage_kind",
                    models.CharField(
                        choices=[
                            ("file_download", "File Download"),
                            ("view", "View"),
                            ("api_access", "API Access"),
                        ],
                        help_text="Type of usage event",
                        max_length=20,
                    ),
                ),
                (
                    "subject_kind",
                    models.CharField(
                        choices=[("resource", "Resource"), ("asset", "Asset")],
                        help_text="Whether tracking resource or asset",
                        max_length=20,
                    ),
                ),
                (
                    "resource_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Resource ID if subject_kind = 'resource'",
                        null=True,
                    ),
                ),
                (
                    "asset_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Asset ID if subject_kind = 'asset'",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional event metadata"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="User IP address", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User browser/client information"
                    ),
                ),
                (
                    "effective_license",
                    models.CharField(
                        choices=[
                            ("CC0", "Creative Commons Zero"),
                            ("CC BY", "Creative Commons Attribution"),
                            ("CC BY-SA", "Creative Commons Attribution-ShareAlike"),
                            ("CC BY-ND", "Creative Commons Attribution-NoDerivs"),
                            ("CC BY-NC", "Creative Commons Attribution-NonCommercial"),
                            (
                                "CC BY-NC-SA",
                                "Creative Commons Attribution-NonCommercial-ShareAlike",
                            ),
                            (
                                "CC BY-NC-ND",
                                "Creative Commons Attribution-NonCommercial-NoDerivs",
                            ),
                            ("Public Domain", "Public Domain"),
                            ("Proprietary", "Proprietary"),
                        ],
                        help_text="License at time of usage",
                        max_length=50,
                    ),
                ),
                (
                    "developer_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("asset_id__isnull", True),
                                ("resource_id__isnull", False),
                                ("subject_kind", "resource"),
                            ),
                            models.Q(
                                ("asset_id__isnull", False),
                                ("resource_id__isnull", True),
                                ("subject_kind", "asset"),
                            ),
                            _connector="OR",
                        ),
                        name="usage_event_subject_kind_consistency",
                    )
                ],
            },
        ),
    ]
