# Generated by Django 5.1.12 on 2025-09-14 01:34

import apps.core.file_uploaders
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete mechanism)",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="License code e.g. 'cc0', 'cc-by-4.0'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Full license name", max_length=255),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, help_text="Abbreviated name", max_length=50
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, help_text="Brief license description"),
                ),
                (
                    "full_text",
                    models.TextField(blank=True, help_text="Complete license text"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Whether this is the default license"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete mechanism)",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Organization name e.g. 'Tafsir Center'",
                        max_length=255,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly slug e.g. 'tafsir-center'", unique=True
                    ),
                ),
                (
                    "icon_url",
                    models.ImageField(
                        blank=True,
                        help_text="Icon/logo image - used in V1 UI: Publisher Page",
                        upload_to=apps.core.file_uploaders.upload_publisher_icon,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "webp",
                                    "svg",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Organization summary - used in V1 UI: Publisher Page",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed organization description"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Organization location", max_length=255
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="Organization website"),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False, help_text="Whether organization is verified"
                    ),
                ),
                (
                    "social_links",
                    models.JSONField(
                        blank=True, default=dict, help_text="Social media links as JSON"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email for the organization",
                        max_length=254,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PublisherMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete mechanism)",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("manager", "Manager")],
                        help_text="Member's role in the organization, just for information. This field WILL NOT be used for permission checks. or any code checks",
                        max_length=20,
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="content.publisher",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publisher_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("publisher", "user")},
            },
        ),
        migrations.AddField(
            model_name="publisher",
            name="members",
            field=models.ManyToManyField(
                related_name="publishers",
                through="content.PublisherMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete mechanism)",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Resource name e.g. 'Tafsir Ibn Katheer CSV'",
                        max_length=255,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL slug e.g. 'tafsir-ibn-katheer-csv'"
                    ),
                ),
                ("description", models.TextField(help_text="Resource description")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("recitation", "Recitation"),
                            ("mushaf", "Mushaf"),
                            ("tafsir", "Tafsir"),
                        ],
                        help_text="Simple options in V1",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("ready", "Ready")],
                        default="draft",
                        help_text="V1: ready = ready to extract Assets from",
                        max_length=20,
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="content.publisher",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete mechanism)",
                    ),
                ),
                ("name", models.CharField(help_text="Asset name", max_length=255)),
                ("description", models.TextField(help_text="Asset description")),
                (
                    "long_description",
                    models.TextField(blank=True, help_text="Extended description"),
                ),
                (
                    "thumbnail_url",
                    models.ImageField(
                        blank=True,
                        help_text="Asset thumbnail image",
                        upload_to=apps.core.file_uploaders.upload_asset_thumbnails,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"]
                            )
                        ],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("recitation", "Recitation"),
                            ("mushaf", "Mushaf"),
                            ("tafsir", "Tafsir"),
                        ],
                        help_text="Asset category matching resource categories",
                        max_length=20,
                    ),
                ),
                (
                    "file_size",
                    models.CharField(
                        help_text="Human readable file size e.g. '2.5 MB'",
                        max_length=50,
                    ),
                ),
                ("format", models.CharField(help_text="File format", max_length=50)),
                (
                    "encoding",
                    models.CharField(
                        default="UTF-8", help_text="Text encoding", max_length=50
                    ),
                ),
                ("version", models.CharField(help_text="Asset version", max_length=50)),
                (
                    "language",
                    models.CharField(help_text="Asset language code", max_length=10),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="content.license",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="content.resource",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResourceVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete mechanism)",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Version name - V1: same as resource name, V2: updates on content",
                        max_length=255,
                    ),
                ),
                ("summary", models.TextField(blank=True, help_text="Version summary")),
                (
                    "semvar",
                    models.CharField(
                        help_text="Semantic versioning e.g. '1.0.0' - core to bind with an AssetVersion",
                        max_length=20,
                    ),
                ),
                (
                    "storage_url",
                    models.FileField(
                        help_text="File storage for resource version",
                        upload_to=apps.core.file_uploaders.upload_resource_files,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "txt",
                                    "zip",
                                    "tar",
                                    "gz",
                                    "json",
                                    "xml",
                                    "csv",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("excel", "Excel"),
                            ("json", "JSON"),
                            ("zip", "ZIP"),
                        ],
                        help_text="File type",
                        max_length=20,
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(
                        default=0, help_text="File size in bytes"
                    ),
                ),
                (
                    "is_latest",
                    models.BooleanField(
                        default=False, help_text="Whether this is the latest version"
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="content.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Version",
                "verbose_name_plural": "Resource Versions",
                "unique_together": {("resource", "semvar")},
            },
        ),
        migrations.CreateModel(
            name="AssetVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete mechanism)",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Asset version name", max_length=255),
                ),
                (
                    "summary",
                    models.TextField(blank=True, help_text="Asset version summary"),
                ),
                (
                    "file_url",
                    models.FileField(
                        blank=True,
                        help_text="Direct file for asset",
                        null=True,
                        upload_to=apps.core.file_uploaders.upload_asset_files,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "txt",
                                    "zip",
                                    "tar",
                                    "gz",
                                    "json",
                                    "xml",
                                    "csv",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(help_text="File size in bytes"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="content.asset",
                    ),
                ),
                (
                    "resource_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_versions",
                        to="content.resourceversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Version",
                "verbose_name_plural": "Asset Versions",
            },
        ),
        migrations.CreateModel(
            name="AssetAccessRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete mechanism)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "developer_access_reason",
                    models.TextField(
                        help_text="Reason for requesting access - used in V1 UI"
                    ),
                ),
                (
                    "intended_use",
                    models.CharField(
                        choices=[
                            ("commercial", "Commercial"),
                            ("non-commercial", "Non-Commercial"),
                        ],
                        help_text="Commercial or non-commercial use",
                        max_length=20,
                    ),
                ),
                (
                    "admin_response",
                    models.TextField(blank=True, help_text="Admin response message"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="When request was approved", null=True
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_asset_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_requests",
                        to="content.asset",
                    ),
                ),
                (
                    "developer_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Access Request",
                "verbose_name_plural": "Asset Access Requests",
                "unique_together": {("developer_user", "asset")},
            },
        ),
    ]
