# Generated by Django 5.2.6 on 2025-09-20 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="license",
            field=models.CharField(
                choices=[
                    ("CC0", "Creative Commons Zero"),
                    ("CC-BY", "Creative Commons Attribution"),
                    ("CC-BY-SA", "Creative Commons Attribution-ShareAlike"),
                    ("CC-BY-ND", "Creative Commons Attribution-NoDerivs"),
                    ("CC-BY-NC", "Creative Commons Attribution-NonCommercial"),
                    (
                        "CC-BY-NC-SA",
                        "Creative Commons Attribution-NonCommercial-ShareAlike",
                    ),
                    (
                        "CC-BY-NC-ND",
                        "Creative Commons Attribution-NonCommercial-NoDerivs",
                    ),
                ],
                help_text="Asset license",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="assetaccess",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="assetaccess",
            name="effective_license",
            field=models.CharField(
                choices=[
                    ("CC0", "Creative Commons Zero"),
                    ("CC-BY", "Creative Commons Attribution"),
                    ("CC-BY-SA", "Creative Commons Attribution-ShareAlike"),
                    ("CC-BY-ND", "Creative Commons Attribution-NoDerivs"),
                    ("CC-BY-NC", "Creative Commons Attribution-NonCommercial"),
                    (
                        "CC-BY-NC-SA",
                        "Creative Commons Attribution-NonCommercial-ShareAlike",
                    ),
                    (
                        "CC-BY-NC-ND",
                        "Creative Commons Attribution-NonCommercial-NoDerivs",
                    ),
                ],
                help_text="Access license at time of grant",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="assetaccessrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="assetpreview",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="assetversion",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="assetversion",
            name="size_bytes",
            field=models.PositiveBigIntegerField(
                default=0, help_text="File size in bytes"
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="asset_version",
            field=models.ForeignKey(
                help_text="Asset version that this distribution provides access to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distributions",
                to="content.assetversion",
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="channel",
            field=models.CharField(
                choices=[
                    ("FILE_DOWNLOAD", "File Download"),
                    ("API", "API"),
                    ("PACKAGE", "Package"),
                ],
                help_text="Channel for accessing the asset",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="license",
            field=models.CharField(
                choices=[
                    ("CC0", "Creative Commons Zero"),
                    ("CC-BY", "Creative Commons Attribution"),
                    ("CC-BY-SA", "Creative Commons Attribution-ShareAlike"),
                    ("CC-BY-ND", "Creative Commons Attribution-NoDerivs"),
                    ("CC-BY-NC", "Creative Commons Attribution-NonCommercial"),
                    (
                        "CC-BY-NC-SA",
                        "Creative Commons Attribution-NonCommercial-ShareAlike",
                    ),
                    (
                        "CC-BY-NC-ND",
                        "Creative Commons Attribution-NonCommercial-NoDerivs",
                    ),
                ],
                default="CC0",
                help_text="Asset license",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="resourceversion",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="usageevent",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="usageevent",
            name="effective_license",
            field=models.CharField(
                choices=[
                    ("CC0", "Creative Commons Zero"),
                    ("CC-BY", "Creative Commons Attribution"),
                    ("CC-BY-SA", "Creative Commons Attribution-ShareAlike"),
                    ("CC-BY-ND", "Creative Commons Attribution-NoDerivs"),
                    ("CC-BY-NC", "Creative Commons Attribution-NonCommercial"),
                    (
                        "CC-BY-NC-SA",
                        "Creative Commons Attribution-NonCommercial-ShareAlike",
                    ),
                    (
                        "CC-BY-NC-ND",
                        "Creative Commons Attribution-NonCommercial-NoDerivs",
                    ),
                ],
                help_text="License at time of usage",
                max_length=50,
            ),
        ),
    ]
