# Generated by Django 5.2.6 on 2025-09-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_alter_asset_created_at_alter_asset_license_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetpreview",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assetpreview",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
