# Generated by Django 5.2.6 on 2025-11-11 13:48

import django.core.validators
from django.db import migrations, models

import apps.core.uploads


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_reciter_riwayah_recitationsurahtrack_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="assetaccessrequest",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="assetpreview",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="assetversion",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="distribution",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="recitationayahtiming",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="recitationsurahtrack",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="resourceversion",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="usageevent",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="recitationsurahtrack",
            name="audio_file",
            field=models.FileField(
                help_text="Per-surah audio file (MP3)",
                upload_to=apps.core.uploads.upload_to_recitation_surah_track_files,
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=["mp3"])
                ],
            ),
        ),
    ]
