# Generated by Django 4.2.23 on 2025-09-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_create_access_control_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetaccess',
            name='is_active',
        ),
        migrations.AddField(
            model_name='publishingorganization',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email for the organization', max_length=254),
        ),
        migrations.AlterField(
            model_name='publishingorganization',
            name='website',
            field=models.URLField(blank=True, help_text='Organization website URL'),
        ),
    ]
