# Generated by Django 5.2.9 on 2025-12-29 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_remove_recitationsurahtrack_surah_name_ar_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="usageevent",
            name="usage_event_subject_kind_consistency",
        ),
        migrations.AlterField(
            model_name="usageevent",
            name="developer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usage_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="usageevent",
            name="subject_kind",
            field=models.CharField(
                choices=[("resource", "Resource"), ("asset", "Asset"), ("public_api", "Public API")],
                help_text="Whether tracking resource or asset",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="usageevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("asset_id__isnull", True), ("resource_id__isnull", False), ("subject_kind", "resource")),
                    models.Q(("asset_id__isnull", False), ("resource_id__isnull", True), ("subject_kind", "asset")),
                    models.Q(("asset_id__isnull", True), ("resource_id__isnull", True), ("subject_kind", "public_api")),
                    _connector="OR",
                ),
                name="usage_event_subject_kind_consistency",
            ),
        ),
    ]
