# Generated by Django 5.2.6 on 2025-12-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_remove_recitationsurahtrack_chapter_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reciter",
            name="name_en",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="riwayah",
            name="name_en",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="reciter",
            name="name_ar",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="riwayah",
            name="name_ar",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
