# Generated by Django 5.2.6 on 2025-12-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_reciter_name_en_riwayah_name_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recitationsurahtrack",
            name="surah_name",
        ),
        migrations.RemoveField(
            model_name="recitationsurahtrack",
            name="surah_name_en",
        ),
    ]
