# Generated by Django 5.2.6 on 2026-01-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_alter_resourceversion_storage_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resourceversion",
            name="file_type",
        ),
        migrations.RemoveField(
            model_name="resourceversion",
            name="is_latest",
        ),
    ]
