# Generated by Django 5.2.10 on 2026-01-22 15:11

import apps.core.uploads
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_remove_resourceversion_file_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="madd_level",
            field=models.CharField(
                blank=True,
                choices=[("twassut", "Twassut"), ("qasr", "Qasr")],
                help_text="Madd level for recitation assets",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="meem_behaviour",
            field=models.CharField(
                blank=True,
                choices=[("silah", "Silah"), ("skoun", "Skoun")],
                help_text="Meem behaviour for recitation assets",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="year",
            field=models.PositiveIntegerField(
                blank=True, help_text="Year of recording for recitation assets", null=True
            ),
        ),
        migrations.AddField(
            model_name="reciter",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reciter",
            name="image_url",
            field=models.ImageField(
                blank=True,
                help_text="Icon/logo image - used in V1 UI: Publisher Page",
                upload_to=apps.core.uploads.upload_to_reciter_image,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif", "webp", "svg"]
                    )
                ],
            ),
        ),
    ]
