# Generated by Django 5.2.6 on 2026-01-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0013_asset_madd_level_asset_meem_behaviour_asset_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recitationsurahtrack",
            name="original_filename",
            field=models.CharField(
                blank=True,
                help_text="Original filename provided at upload time (for audit/debugging; not used as storage key)",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recitationsurahtrack",
            name="upload_finished_at",
            field=models.DateTimeField(blank=True, help_text="When audio file upload was completed", null=True),
        ),
    ]
