# Generated by Django 5.2.11 on 2026-02-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_recitationsurahtrack_original_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciter',
            name='is_contemporary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reciter',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reciter',
            name='nationality_ar',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reciter',
            name='nationality_en',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
