# Generated by Django 5.2.10 on 2026-02-05 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_recitationsurahtrack_original_filename_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Qiraah",
            fields=[
                (
                    "id",
                    models.AutoField(help_text="Unique identifier for this record", primary_key=True, serialize=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when this record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when this record was last updated"),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(allow_unicode=True, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="riwayah",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="riwayah",
            name="name_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="riwayah",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="riwayah",
            name="slug",
            field=models.SlugField(allow_unicode=True),
        ),
        migrations.AddField(
            model_name="riwayah",
            name="qiraah",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent Qiraah (recitation method)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="riwayahs",
                to="content.qiraah",
            ),
        ),
        migrations.AddField(
            model_name="qiraah",
            name="name_ar",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="qiraah",
            name="name_en",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="riwayah",
            unique_together={("qiraah", "name"), ("qiraah", "name_ar"), ("qiraah", "name_en")},
        ),
        migrations.AddIndex(
            model_name="riwayah",
            index=models.Index(fields=["qiraah", "slug"], name="content_riw_qiraah__0ab629_idx"),
        ),
    ]
