# Generated by Django 5.2.11 on 2026-02-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_reciter_is_contemporary_reciter_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciter',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reciter',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reciter',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reciter',
            name='identifier',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
