# Generated by Django 5.2.10 on 2026-02-05 17:17

from django.db import migrations


def create_asim_qiraah(apps, schema_editor):
    """Create the Asim Qiraah and assign all existing Riwayahs to it"""
    Qiraah = apps.get_model("content", "Qiraah")
    Riwayah = apps.get_model("content", "Riwayah")

    # Create Asim Qiraah if it doesn't exist
    asim_qiraah, created = Qiraah.objects.get_or_create(
        name="Asim",
        defaults={
            "slug": "asim",
            "is_active": True,
        }
    )

    # Assign all Riwayahs to Asim Qiraah
    riwayahs = Riwayah.objects.filter(qiraah__isnull=True)
    riwayahs.update(qiraah=asim_qiraah)


def reverse_asim_qiraah(apps, schema_editor):
    """Reverse the operation - remove Asim Qiraah and nullify all Riwayahs"""
    Qiraah = apps.get_model("content", "Qiraah")
    Riwayah = apps.get_model("content", "Riwayah")

    # Clear all Riwayah references to Asim Qiraah
    Riwayah.objects.filter(qiraah__name="Asim").update(qiraah=None)

    # Delete Asim Qiraah
    Qiraah.objects.filter(name="Asim").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_add_qiraah_model"),
    ]

    operations = [
        migrations.RunPython(create_asim_qiraah, reverse_asim_qiraah),
    ]
