# Generated by Django 5.2.10 on 2026-02-05 17:17

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_add_qiraah_model"),
    ]

    operations = [
    ]
