# Generated by Django 5.2.10 on 2026-02-05 17:17

from django.db import migrations


def create_initial_qiraahs(apps, schema_editor):
    """Create Qiraah records for a canonical list and assign matching Riwayahs."""
    from django.utils.text import slugify

    Qiraah = apps.get_model("content", "Qiraah")
    Riwayah = apps.get_model("content", "Riwayah")

    # Define the canonical list: English name, Arabic name, and associated riwayah names
    qiraahs_data = [
        {
            "english": "Imam Nafi al-Madani",
            "arabic": "الإمام نافع المدني",
            "riwayahs": [
                {"english": "Qaloon", "arabic": "قالون"},
                {"english": "Warsh", "arabic": "ورش"},
            ],
        },
        {
            "english": "Imam Ibn Kathir al-Makki",
            "arabic": "الإمام ابن كثير المكي",
            "riwayahs": [
                {"english": "Al-Bazzi", "arabic": "البزي"},
                {"english": "Qunbul", "arabic": "قنبل"},
            ],
        },
        {
            "english": "Imam Abu Amr al-Basri",
            "arabic": "الإمام أبو عمرو البصري",
            "riwayahs": [
                {"english": "ad-Duri", "arabic": "الدوري"},
                {"english": "as-Susi", "arabic": "السوسي"},
            ],
        },
        {
            "english": "Imam Ibn Amir ash-Shami",
            "arabic": "الإمام ابن عامر الشامي",
            "riwayahs": [
                {"english": "Hisham", "arabic": "هشام"},
                {"english": "Ibn Daqwan", "arabic": "ابن ذكوان"},
            ],
        },
        {
            "english": "Imam Asim al-Kufi",
            "arabic": "الإمام عاصم الكوفي",
            "riwayahs": [
                {"english": "Shu'bah", "arabic": "شعبة"},
                {"english": "Hafs", "arabic": "حفص"},
            ],
        },
        {
            "english": "Imam Hamzah al-Kufi",
            "arabic": "الإمام حمزة الكوفي",
            "riwayahs": [
                {"english": "Khalaf", "arabic": "خلف"},
                {"english": "Khalad", "arabic": "خلاد"},
            ],
        },
        {
            "english": "Imam al-Kisai al-Kufi",
            "arabic": "الإمام الكسائي الكوفي",
            "riwayahs": [
                {"english": "Abu al-Harith", "arabic": "أبو الحارث"},
                {"english": "ad-Duri", "arabic": "الدوري"},
            ],
        },
        {
            "english": "Imam Abu Ja'far al-Madani",
            "arabic": "الإمام أبو جعفر المدني",
            "riwayahs": [
                {"english": "Ibn Wardan", "arabic": "ابن وردان"},
                {"english": "Ibn Jummaz", "arabic": "ابن جماز"},
            ],
        },
        {
            "english": "Imam Ya'qub al-Hadrami al-Basri",
            "arabic": "الإمام يعقوب الحضرمي البصري",
            "riwayahs": [
                {"english": "Ruwis", "arabic": "رويس"},
                {"english": "Ruh", "arabic": "روح"},
            ],
        },
        {
            "english": "Imam Khalf ibn Hisham al-Ashir al-Kufi",
            "arabic": "الإمام خلف بن هشام العاشر الكوفي",
            "riwayahs": [
                {"english": "Ishaq", "arabic": "إسحاق"},
                {"english": "Idris", "arabic": "إدريس"},
            ],
        },
    ]


    for item in qiraahs_data:
        english = item["english"]
        arabic = item["arabic"]
        slug = slugify(english[:50], allow_unicode=True)


        qiraah, created = Qiraah.objects.update_or_create(
            slug=slug,
            name = english,
            defaults={
                "name_ar" : arabic,
                "is_active": True,
            },
        )



        # Assign or create matching Riwayahs to this qiraah where possible.
        for r in item.get("riwayahs", []):
            # r can be either a string (english) or a dict {english, arabic}
            if isinstance(r, dict):
                r_english = r.get("english")
                r_arabic = r.get("arabic")
            else:
                # assume english name provided, try to find arabic by simple map fallback
                r_english = r
                r_arabic = None

            rslug = slugify((r_english or "")[:50], allow_unicode=True)

            # Try to find existing riwayah by slug or name
            matches = Riwayah.objects.filter(slug__iexact=rslug)
            if not matches.exists() and r_english:
                matches = Riwayah.objects.filter(name__iexact=r_english)
            if not matches.exists() and r_english:
                matches = Riwayah.objects.filter(name__icontains=r_english)

            if matches.exists():
                # If exists, assign to qiraah
                matches.update(qiraah=qiraah)

                # create the riwayah and associate
                Riwayah.objects.update_or_create(name=r_english, name_ar=r_arabic, slug=rslug, is_active=True, qiraah=qiraah)


def reverse_initial_qiraahs(apps, schema_editor):
    """Remove created Qiraah entries and clear Riwayah assignments made by this migration."""
    Qiraah = apps.get_model("content", "Qiraah")
    Riwayah = apps.get_model("content", "Riwayah")

    # Clear riwayah qiraah assignments for the qiraahs we created (match by slug where possible)
    slugs_to_remove = [
        "imam-nafi-al-madani",
        "imam-ibn-kathir-al-makki",
        "imam-abu-amr-al-basri",
        "imam-ibn-amir-ash-shami",
        "imam-asim-al-kufi",
        "imam-hamzah-al-kufi",
        "imam-al-kisai-al-kufi",
        "imam-abu-jafar-al-madani",
        "imam-yaqub-al-hadrami-al-basri",
        "imam-khalf-ibn-hisham-al-ashir-al-kufi",
    ]

    # For each qiraah slug, nullify riwayah.qiraah if it points to that qiraah
    for slug in slugs_to_remove:
        try:
            q = Qiraah.objects.get(slug=slug)
            Riwayah.objects.filter(qiraah=q).update(qiraah=None)
            q.delete()
        except Qiraah.DoesNotExist:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_add_qiraah_model"),
    ]

    operations = [
        migrations.RunPython(create_initial_qiraahs, reverse_initial_qiraahs),
    ]
