# Generated by Django 5.2.10 on 2026-02-05 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_populate_qiraah"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riwayah",
            name="qiraah",
            field=models.ForeignKey(
                help_text="Parent Qiraah (recitation method)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="riwayahs",
                to="content.qiraah",
            ),
        ),
    ]
