# Generated by Django 5.2.10 on 2026-02-09 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0017_make_qiraah_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="qiraah",
            field=models.ForeignKey(
                blank=True,
                help_text="Qiraah for recitation assets",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="content.qiraah",
            ),
        ),
    ]
