# Generated by Django 5.2.10 on 2026-02-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0017_make_qiraah_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="qiraah",
            name="name_ar",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="qiraah",
            name="name_en",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
