# Generated by Django 5.2.10 on 2026-02-09 12:40

from django.db import migrations


def populate_asset_qiraah(apps, schema_editor):
    """Populate Asset.qiraah from the related Asset.riwayah.qiraah when available."""
    Asset = apps.get_model("content", "Asset")
    # Use an F expression to set the FK directly from the related riwayah relationship
    from django.db.models import F

    # Only set qiraah where riwayah is present and riwayah.qiraah is not null
    recitations = Asset.objects.filter(riwayah__isnull=False, riwayah__qiraah__isnull=False)
    objects = []
    for recitation in recitations:
        recitation.qiraah_id = recitation.riwayah.qiraah_id
        objects.append(recitation)
    Asset.objects.bulk_update(objects, ["qiraah_id"])


def reverse_populate_asset_qiraah(apps, schema_editor):
    """Reverse operation: clear Asset.qiraah for assets that were populated from their riwayah."""
    Asset = apps.get_model("content", "Asset")

    # Clear qiraah for assets that currently have a riwayah (best-effort reversal)
    Asset.objects.filter(riwayah__isnull=False).update(qiraah=None)


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0018_asset_qiraah"),
    ]

    operations = [
        migrations.RunPython(populate_asset_qiraah, reverse_populate_asset_qiraah),
    ]
