# Generated by Django 5.2.10 on 2026-02-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0019_auto_20260209_1540"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="asset",
            name="asset_recitation_fields_consistency",
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("category", "recitation"), ("qiraah__isnull", False), ("reciter__isnull", False)),
                    models.Q(
                        models.Q(("category", "recitation"), _negated=True),
                        ("qiraah__isnull", True),
                        ("reciter__isnull", True),
                        ("riwayah__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="asset_recitation_fields_consistency",
            ),
        ),
    ]
