# Generated by Django 5.2.10 on 2026-02-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0020_remove_asset_asset_recitation_fields_consistency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="category",
            field=models.CharField(
                choices=[
                    ("recitation", "Recitation"),
                    ("mushaf", "Mushaf"),
                    ("tafsir", "Tafsir"),
                    ("program", "Program"),
                    ("linguistic", "Linguistic"),
                    ("translation", "Translation"),
                    ("font", "Font"),
                    ("search", "Search"),
                    ("tajweed", "Tajweed"),
                ],
                help_text="Asset category matching resource categories",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="category",
            field=models.CharField(
                choices=[
                    ("recitation", "Recitation"),
                    ("mushaf", "Mushaf"),
                    ("tafsir", "Tafsir"),
                    ("program", "Program"),
                    ("linguistic", "Linguistic"),
                    ("translation", "Translation"),
                    ("font", "Font"),
                    ("search", "Search"),
                    ("tajweed", "Tajweed"),
                ],
                help_text="Simple options in V1",
                max_length=20,
            ),
        ),
    ]
