# Generated by Django 5.2.10 on 2026-02-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0020_remove_asset_asset_recitation_fields_consistency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="is_external",
            field=models.BooleanField(default=False),
        ),
    ]
