# Generated by Django 5.2.10 on 2026-02-16 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0022_resource_is_external"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentIssueReport",
            fields=[
                (
                    "id",
                    models.AutoField(help_text="Unique identifier for this record", primary_key=True, serialize=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when this record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when this record was last updated"),
                ),
                ("object_id", models.PositiveIntegerField(help_text="ID of the reported content object")),
                ("description", models.TextField(help_text="Description of the issue (10-2000 characters)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        help_text="Current status of the issue report",
                        max_length=20,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Django ContentType for the reported object",
                        limit_choices_to={"model__in": ["resource", "asset"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        help_text="User who reported the issue",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_issue_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Issue Report",
                "verbose_name_plural": "Content Issue Reports",
                "indexes": [
                    models.Index(fields=["content_type", "object_id"], name="content_con_content_c433ad_idx"),
                    models.Index(fields=["reporter", "status"], name="content_con_reporte_570fcc_idx"),
                    models.Index(fields=["status", "created_at"], name="content_con_status_4c9eec_idx"),
                ],
            },
        ),
    ]
