# Generated by Django 5.2.10 on 2026-02-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0023_contentissuereport"),
        ("publishers", "0006_alter_publisher_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="external_url",
            field=models.URLField(
                blank=True,
                help_text="If is_external=True, URL to the external resource",
                null=True,
                verbose_name="External URL",
            ),
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("external_url__isnull", True), ("is_external", False)),
                    models.Q(("external_url__isnull", False), ("is_external", True)),
                    _connector="OR",
                ),
                name="resource_external_url_consistency",
            ),
        ),
    ]
