# Generated by Django 5.2.10 on 2026-02-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0024_resource_external_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qiraah",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="qiraah",
            name="bio_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="qiraah",
            name="bio_en",
            field=models.TextField(blank=True, null=True),
        ),
    ]
