# Generated by Django 5.2.11 on 2026-02-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_qiraah_bio_qiraah_bio_ar_qiraah_bio_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciter',
            name='bio_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reciter',
            name='bio_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riwayah',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='riwayah',
            name='bio_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riwayah',
            name='bio_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
