# Generated by Django 5.2.11 on 2026-02-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0025_qiraah_bio_qiraah_bio_ar_qiraah_bio_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="recitation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("murattal", "Murattal"),
                    ("mujawwad", "Mujawwad"),
                    ("muallim", "Muallim"),
                    ("taalim", "Taalim"),
                ],
                help_text="Recitation style: Murattal (مرتل), Mujawwad (مجود), etc.",
                max_length=20,
                null=True,
            ),
        ),
    ]
