# Generated by Django 5.2.11 on 2026-02-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0025_qiraah_bio_qiraah_bio_ar_qiraah_bio_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="reciter",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reciter",
            name="date_of_death",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reciter",
            name="nationality",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
