# Generated by Django 5.2.11 on 2026-03-03 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0026_reciter_bio_ar_reciter_bio_en_riwayah_bio_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="usageevent",
            name="asset_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, help_text="Asset ID if subject_kind = 'asset'", null=True
            ),
        ),
        migrations.AlterField(
            model_name="usageevent",
            name="resource_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, help_text="Resource ID if subject_kind = 'resource'", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="assetaccess",
            index=models.Index(fields=["asset"], name="assetaccess_asset_idx"),
        ),
        migrations.AddIndex(
            model_name="usageevent",
            index=models.Index(fields=["developer_user", "usage_kind"], name="usageevent_user_kind_idx"),
        ),
    ]
