# Generated by Django 5.2.11 on 2026-02-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0026_add_recitation_type_to_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="recitationsurahtrack",
            name="bitrate",
            field=models.PositiveIntegerField(blank=True, help_text="Audio bitrate in kbps (e.g. 128, 64)", null=True),
        ),
    ]
