# Generated by Django 5.2.11 on 2026-02-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0026_reciter_date_of_birth_reciter_date_of_death_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reciter",
            name="reciter_identifier",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
