# Generated by Django 5.2.11 on 2026-02-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0027_reciter_reciter_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reciter",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="reciter",
            name="date_of_death",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="reciter",
            name="nationality",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="reciter",
            name="reciter_identifier",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
