# Generated by Django 5.2.11 on 2026-03-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0027_add_bitrate_to_track"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recitationsurahtrack",
            name="bitrate",
        ),
    ]
