# Generated by Django 5.2.6 on 2026-03-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0027_nationality_reciter_is_contemporary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reciter",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reciter",
            name="date_of_death",
            field=models.DateField(blank=True, null=True),
        ),
    ]
