# Generated by Django 5.2.11 on 2026-03-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0027_add_bitrate_to_track"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recitationsurahtrack",
            name="bitrate",
        ),
        migrations.AddField(
            model_name="qiraah",
            name="recitation_style",
            field=models.CharField(
                blank=True,
                choices=[("murattal", "Murattal / مرتل"), ("mujawwad", "Mujawwad / مجود")],
                help_text="Recitation style: Murattal (مرتل) or Mujawwad (مجود)",
                max_length=20,
                null=True,
                verbose_name="Recitation Style / نوع التلاوة",
            ),
        ),
    ]
