# Generated by Django 5.2.6 on 2026-03-30 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0028_reciter_date_of_birth_reciter_date_of_death"),
    ]

    operations = [
        migrations.AddField(
            model_name="nationality",
            name="name_ar",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="nationality",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="reciter",
            name="nationality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reciters",
                to="content.nationality",
            ),
        ),
    ]
