# Generated by Django 5.2.11 on 2026-02-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0029_alter_reciter_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reciter",
            name="date_of_death",
            field=models.DateField(blank=True, null=True),
        ),
    ]
