# Generated by Django 5.2.6 on 2026-03-31 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0029_nationality_name_ar_nationality_name_en_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="assetaccessrequest",
            index=models.Index(fields=["developer_user", "asset"], name="content_ass_develop_5a7e20_idx"),
        ),
        migrations.AddIndex(
            model_name="usageevent",
            index=models.Index(fields=["developer_user", "usage_kind"], name="content_usa_develop_a8d560_idx"),
        ),
        migrations.AddIndex(
            model_name="usageevent",
            index=models.Index(fields=["created_at", "usage_kind"], name="content_usa_created_638bb6_idx"),
        ),
    ]
