# Generated by Django 5.2.11 on 2026-04-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0030_add_missing_db_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="external_url",
            field=models.URLField(
                blank=True, help_text="URL for external assets", null=True, verbose_name="External URL"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="is_external",
            field=models.BooleanField(default=False, help_text="Whether this asset is external"),
        ),
    ]
