# Generated by Django 5.2.11 on 2026-04-06 00:18

from django.db import migrations


def populate_asset_external_fields(apps, schema_editor):
    """Populate asset.is_external and asset.external_url from resource fields"""
    Asset = apps.get_model("content", "Asset")
    db_alias = schema_editor.connection.alias
    for asset in Asset.objects.using(db_alias).select_related("resource").iterator(chunk_size=1000):
        asset.is_external = asset.resource.is_external
        asset.external_url = asset.resource.external_url
        asset.save(update_fields=["is_external", "external_url"])


def reverse_populate(apps, schema_editor):
    """Reverse the population"""
    Asset = apps.get_model("content", "Asset")
    db_alias = schema_editor.connection.alias
    Asset.objects.using(db_alias).update(is_external=False, external_url=None)


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0031_asset_external_url_asset_is_external"),
    ]

    operations = [
        migrations.RunPython(populate_asset_external_fields, reverse_populate),
    ]
