# Generated by Django 5.2.11 on 2026-04-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0032_populate_asset_external_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, default="", help_text="URL-friendly slug for the asset"
            ),
        ),
    ]
