# Generated by Django 5.2.11 on 2026-04-06 00:35

from django.db import migrations
from django.utils.text import slugify


def populate_asset_slug(apps, schema_editor):
    """Populate slug field from name field for all assets"""
    Asset = apps.get_model("content", "Asset")
    db_alias = schema_editor.connection.alias
    existing_slugs: set[str] = set(Asset.objects.using(db_alias).values_list("slug", flat=True))

    for asset in Asset.objects.using(db_alias).iterator(chunk_size=1000):
        if not asset.slug:
            # Prefer name_en, fallback to name_ar, then name, then pk-based default
            base_name = (
                getattr(asset, "name_en", None)
                or getattr(asset, "name_ar", None)
                or asset.name
                or f"asset-{asset.pk}"
            )
            base_slug = slugify(base_name[:50], allow_unicode=True) or f"asset-{asset.pk}"
            slug = base_slug
            counter = 1
            while slug in existing_slugs:
                slug = f"{base_slug[:40]}-{counter}"
                counter += 1
            existing_slugs.add(slug)
            asset.slug = slug
            asset.save(update_fields=["slug"])


def reverse_populate_slug(apps, schema_editor):
    """Clear slug field on reverse"""
    Asset = apps.get_model("content", "Asset")
    Asset.objects.all().update(slug="")


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0033_add_asset_slug"),
    ]

    operations = [
        migrations.RunPython(populate_asset_slug, reverse_populate_slug),
    ]
