# Generated by Django 5.2.11 on 2026-04-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0035_make_asset_slug_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, default="", help_text="URL-friendly slug for the asset", unique=True
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("external_url__isnull", True), ("is_external", False)),
                    models.Q(("external_url__isnull", False), ("is_external", True)),
                    _connector="OR",
                ),
                name="asset_external_url_consistency",
            ),
        ),
    ]
