# Generated by Django 5.2.11 on 2026-04-07 23:01

import django_countries.fields
from django.db import migrations


def backfill_nationalities(apps, schema_editor):
    Reciter = apps.get_model("content", "Reciter")
    Nationality = apps.get_model("content", "Nationality")
    for reciter in Reciter.objects.all():
        if reciter.nationality and str(reciter.nationality).isdigit():
            nat_id = int(reciter.nationality)
            try:
                nat = Nationality.objects.get(id=nat_id)
                reciter.nationality = nat.code
                reciter.save(update_fields=["nationality"])
            except Nationality.DoesNotExist:
                reciter.nationality = ""
                reciter.save(update_fields=["nationality"])


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0036_asset_external_url_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reciter",
            name="nationality",
            field=django_countries.fields.CountryField(blank=True, default="", max_length=2),
        ),
        migrations.RemoveField(
            model_name="reciter",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="reciter",
            name="is_contemporary",
        ),
        migrations.RunPython(backfill_nationalities, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="Nationality",
        ),
    ]
