# Generated by Django 5.2.13 on 2026-04-21 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0037_alter_reciter_nationality_and_more"),
        ("publishers", "0007_add_foundation_year_and_country_to_publisher"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                help_text="Publisher owning this asset (backfilled from Resource; non-null after 0040)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="publishers.publisher",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("draft", "Draft"), ("ready", "Ready")],
                help_text="Asset status (backfilled from Resource; non-null after 0040)",
                max_length=20,
                null=True,
            ),
        ),
    ]
