# Generated by Django 5.2.13 on 2026-04-21 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0039_backfill_resource_data_into_asset"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("publishers", "0007_add_foundation_year_and_country_to_publisher"),
    ]

    operations = [

        migrations.RemoveField(
            model_name="asset",
            name="resource",
        ),

        migrations.RemoveField(
            model_name="assetversion",
            name="resource_version",
        ),
        migrations.RemoveConstraint(
            model_name="usageevent",
            name="usage_event_subject_kind_consistency",
        ),
        migrations.RemoveField(
            model_name="usageevent",
            name="resource_id",
        ),
        migrations.RemoveField(
            model_name="usageevent",
            name="subject_kind",
        ),
        migrations.AlterField(
            model_name="asset",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="assets", to="publishers.publisher"
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(choices=[("draft", "Draft"), ("ready", "Ready")], default="draft", max_length=20),
        ),
        migrations.AlterField(
            model_name="contentissuereport",
            name="content_type",
            field=models.ForeignKey(
                help_text="Django ContentType for the reported object",
                limit_choices_to={"model__in": ["asset"]},
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="usageevent",
            name="asset_id",
            field=models.PositiveIntegerField(help_text="Asset ID the event refers to"),
        ),
        migrations.DeleteModel(
            name="Resource",
        ),
        migrations.DeleteModel(
            name="ResourceVersion",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="version",
        ),
    ]
