# Generated by Django 5.2.13 on 2026-05-05 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_remove_resource_publisher_remove_asset_resource_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contentissuereport',
            name='content_con_content_c433ad_idx',
        ),
        migrations.RemoveField(
            model_name='contentissuereport',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='contentissuereport',
            name='object_id',
        ),
        migrations.AddField(
            model_name='contentissuereport',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Asset being reported', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to='content.asset'),
        ),
        migrations.AddIndex(
            model_name='contentissuereport',
            index=models.Index(fields=['asset'], name='content_con_asset_i_a1bb25_idx'),
        ),
    ]
