# Generated by Django 5.2.14 on 2026-06-16 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_reslug_with_english_based_logic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetaccessrequest',
            name='admin_response',
        ),
        migrations.AddField(
            model_name='assetaccessrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When request was rejected', null=True),
        ),
        migrations.AddField(
            model_name='assetaccessrequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_asset_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetaccessrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason shown to the developer when a request is rejected'),
        ),
    ]
