# Generated by Django 5.2.14 on 2026-06-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0043_remove_assetaccessrequest_admin_response_and_more'),
        ('publishers', '0012_publisher_auto_accept_access_requests'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asset',
            name='asset_recitation_fields_consistency',
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category', 'recitation'), ('qiraah__isnull', False), ('reciter__isnull', False)), models.Q(models.Q(('category', 'recitation'), _negated=True), ('reciter__isnull', True)), _connector='OR'), name='asset_recitation_fields_consistency'),
        ),
    ]
