# Generated by Django 5.2.14 on 2026-06-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0044_remove_asset_asset_recitation_fields_consistency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_open_access',
            field=models.BooleanField(default=False, help_text='If true, the asset can be consumed directly without going through the access-request cycle.'),
        ),
        migrations.AddField(
            model_name='asset',
            name='restricted_for_tenant',
            field=models.BooleanField(default=False, help_text="If true, the asset is restricted to the publisher's tenant surface (their own website/API) and is hidden from public surfaces (the CMS assets website and the public developers API). If false (default), the asset is available everywhere."),
        ),
    ]
