# Generated by Django 5.2.14 on 2026-07-02 09:58

from django.db import migrations, models


def set_existing_assets_open_access(apps, schema_editor):
    Asset = apps.get_model('content', 'Asset')
    Asset.objects.filter(is_open_access=False).update(is_open_access=True)


def revert_existing_assets_open_access(apps, schema_editor):
    Asset = apps.get_model('content', 'Asset')
    Asset.objects.filter(is_open_access=True).update(is_open_access=False)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0045_asset_is_open_access_asset_restricted_for_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='is_open_access',
            field=models.BooleanField(default=True, help_text='Flag to allow consuming the asset directly without the access-request cycle (default enabled).'),
        ),
        migrations.RunPython(
            set_existing_assets_open_access,
            revert_existing_assets_open_access,
        ),
    ]
