# Generated by Django 5.2.14 on 2026-08-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_merge_20260826_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetversionentry',
            name='footnotes',
        ),
    ]
