# Generated by Django 5.2.14 on 2026-09-06 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0054_recitationfolder_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLanguage',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('language', models.CharField(help_text="Language code, e.g. 'ar', 'es'", max_length=10)),
                ('is_source', models.BooleanField(default=False, help_text="True for the asset's original/source language (at most one per asset).")),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='content.asset')),
            ],
        ),
        migrations.AddField(
            model_name='assetversion',
            name='asset_language',
            field=models.ForeignKey(blank=True, help_text='Language rendition this version belongs to (defaults to the source language).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='content.assetlanguage'),
        ),
        migrations.AddConstraint(
            model_name='assetlanguage',
            constraint=models.UniqueConstraint(fields=('asset', 'language'), name='unique_language_per_asset'),
        ),
        migrations.AddConstraint(
            model_name='assetlanguage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_source', True)), fields=('asset',), name='unique_source_language_per_asset'),
        ),
    ]
