# Generated by Django 5.2.14 on 2026-09-07 16:23

import apps.core.uploads
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0054_recitationfolder_is_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="recitationayahtiming",
            name="audio_file",
            field=models.FileField(
                blank=True,
                help_text="Sliced per-ayah audio file (MP3); populated by the slicing pipeline.",
                null=True,
                upload_to=apps.core.uploads.upload_to_recitation_ayah_audio,
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["mp3"])],
            ),
        ),
        migrations.AddField(
            model_name="recitationayahtiming",
            name="size_bytes",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="Sliced audio file size in bytes (auto-calculated on save when audio_file is present).",
            ),
        ),
    ]
