# Generated by Django 5.2.14 on 2026-09-09 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0058_recitationayahtiming_audio_file_size_bytes'),
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetVersionChange',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('change_type', models.CharField(choices=[('added', 'Added'), ('modified', 'Modified'), ('removed', 'Removed')], max_length=10)),
                ('old_text', models.TextField(blank=True, help_text='Previous text; empty for added')),
                ('new_text', models.TextField(blank=True, help_text='New text; empty for removed')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ayah index, for display ordering')),
                ('ayah', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quran.ayah')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='content.assetversion')),
            ],
            options={
                'indexes': [models.Index(fields=['version', 'order'], name='content_ass_version_f7de62_idx')],
                'constraints': [models.UniqueConstraint(fields=('version', 'ayah'), name='unique_change_per_version_ayah')],
            },
        ),
    ]
