# Generated by Django 5.2.14 on 2026-09-13 16:37

from django.db import migrations, models


def backfill_language_status(apps, schema_editor):
    """Source renditions stay available (they carry the asset's own content, gated
    by Asset.status); existing translations are hidden until re-marked ready."""
    AssetLanguage = apps.get_model("content", "AssetLanguage")
    AssetLanguage.objects.filter(is_source=True).update(status="ready")
    AssetLanguage.objects.filter(is_source=False).update(status="draft")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0059_assetversionchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlanguage',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready')], default='draft', help_text="Consumer availability of this language rendition. DRAFT hides it from consumers (a translation in progress); READY makes it downloadable. The source language is created READY (the asset's own Asset.status is the overarching gate).", max_length=20),
        ),
        migrations.RunPython(backfill_language_status, noop_reverse),
    ]
