# Generated by Django 5.2.14 on 2026-09-14 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0060_asset_language_status'),
        ('publishers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetVersionChangeReview',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('state', models.CharField(choices=[('approved', 'Approved'), ('commented', 'Commented')], max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Reviewer comment; required when state is commented')),
                ('reviewed_at', models.DateTimeField()),
                ('change', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='content.assetversionchange')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewerLanguage',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('language', models.CharField(help_text="Language code the member may review, e.g. 'fr'", max_length=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_languages', to='publishers.publishermember')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('member', 'language'), name='unique_reviewer_member_language')],
            },
        ),
    ]
