# Generated by Django 5.2.14 on 2026-09-17 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0061_review_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='MushafLayout',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('name', models.CharField(help_text="Layout name, e.g. 'Madani 604'", max_length=128, unique=True)),
                ('name_en', models.CharField(help_text="Layout name, e.g. 'Madani 604'", max_length=128, null=True, unique=True)),
                ('name_ar', models.CharField(help_text="Layout name, e.g. 'Madani 604'", max_length=128, null=True, unique=True)),
                ('page_count', models.PositiveSmallIntegerField(help_text='Number of pages in this mushaf printing', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
