# Generated by Django 5.2.14 on 2026-09-17 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0062_mushaf_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='mushaf_layout',
            field=models.ForeignKey(blank=True, help_text="Pagination this asset follows. Required when template is 'page', forbidden otherwise.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='content.mushaflayout'),
        ),
        migrations.AddField(
            model_name='asset',
            name='template',
            field=models.CharField(blank=True, choices=[('surah', 'Surah based'), ('ayah', 'Ayah based'), ('word', 'Word based'), ('page', 'Page based')], help_text='Content granularity for text assets (translation / tafsir). Chosen at creation and immutable afterwards. NULL for every other category.', max_length=10, null=True),
        ),
    ]
