# Generated by Django 5.2.14 on 2026-09-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0064_backfill_asset_template'),
        ('publishers', '0015_grant_access_all_languages_to_editor_groups'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__in', ['translation', 'tafsir']), ('template__isnull', False)), models.Q(models.Q(('category__in', ['translation', 'tafsir']), _negated=True), ('template__isnull', True)), _connector='OR'), name='asset_template_required_for_text'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mushaf_layout__isnull', False), ('template', 'page'), ('template__isnull', False)), models.Q(models.Q(('template', 'page'), _negated=True), ('mushaf_layout__isnull', True), ('template__isnull', False)), models.Q(('mushaf_layout__isnull', True), ('template__isnull', True)), _connector='OR'), name='asset_mushaf_layout_consistency'),
        ),
    ]
