# Generated by Django 5.2.14 on 2026-09-17 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0065_asset_template_constraints'),
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetversionchange',
            name='page_no',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Page within the asset's MushafLayout — set only for page-template assets", null=True),
        ),
        migrations.AddField(
            model_name='assetversionchange',
            name='sura',
            field=models.ForeignKey(blank=True, help_text='Canonical sura (1-114) — set only for surah-template assets', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quran.sura'),
        ),
        migrations.AddField(
            model_name='assetversionchange',
            name='word',
            field=models.ForeignKey(blank=True, help_text='Canonical word — set only for word-template assets', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quran.word'),
        ),
        migrations.AddField(
            model_name='assetversionentry',
            name='page_no',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Page within the asset's MushafLayout — set only for page-template assets", null=True),
        ),
        migrations.AddField(
            model_name='assetversionentry',
            name='sura',
            field=models.ForeignKey(blank=True, help_text='Canonical sura (1-114) — set only for surah-template assets', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quran.sura'),
        ),
        migrations.AddField(
            model_name='assetversionentry',
            name='word',
            field=models.ForeignKey(blank=True, help_text='Canonical word — set only for word-template assets', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quran.word'),
        ),
        migrations.AlterField(
            model_name='assetversionchange',
            name='ayah',
            field=models.ForeignKey(blank=True, help_text='Canonical ayah (1-6236) — set only for ayah-template assets', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quran.ayah'),
        ),
        migrations.AlterField(
            model_name='assetversionentry',
            name='ayah',
            field=models.ForeignKey(blank=True, help_text='Canonical ayah (1-6236) — set only for ayah-template assets', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quran.ayah'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE content_assetversionchange "
                        "ADD CONSTRAINT change_exactly_one_unit CHECK ("
                        "  (sura_id IS NOT NULL)::int + (ayah_id IS NOT NULL)::int"
                        "+ (word_id IS NOT NULL)::int + (page_no IS NOT NULL)::int = 1"
                        ") NOT VALID"
                    ),
                    reverse_sql="ALTER TABLE content_assetversionchange DROP CONSTRAINT change_exactly_one_unit",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE content_assetversionchange VALIDATE CONSTRAINT change_exactly_one_unit",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name='assetversionchange',
                    constraint=models.CheckConstraint(condition=models.Q(models.Q(('ayah__isnull', True), ('page_no__isnull', True), ('sura__isnull', False), ('word__isnull', True)), models.Q(('ayah__isnull', False), ('page_no__isnull', True), ('sura__isnull', True), ('word__isnull', True)), models.Q(('ayah__isnull', True), ('page_no__isnull', True), ('sura__isnull', True), ('word__isnull', False)), models.Q(('ayah__isnull', True), ('page_no__isnull', False), ('sura__isnull', True), ('word__isnull', True)), _connector='OR'), name='change_exactly_one_unit'),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='assetversionchange',
            constraint=models.UniqueConstraint(fields=('version', 'sura'), name='unique_change_per_version_sura'),
        ),
        migrations.AddConstraint(
            model_name='assetversionchange',
            constraint=models.UniqueConstraint(fields=('version', 'word'), name='unique_change_per_version_word'),
        ),
        migrations.AddConstraint(
            model_name='assetversionchange',
            constraint=models.UniqueConstraint(fields=('version', 'page_no'), name='unique_change_per_version_page'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE content_assetversionentry "
                        "ADD CONSTRAINT entry_exactly_one_unit CHECK ("
                        "  (sura_id IS NOT NULL)::int + (ayah_id IS NOT NULL)::int"
                        "+ (word_id IS NOT NULL)::int + (page_no IS NOT NULL)::int = 1"
                        ") NOT VALID"
                    ),
                    reverse_sql="ALTER TABLE content_assetversionentry DROP CONSTRAINT entry_exactly_one_unit",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE content_assetversionentry VALIDATE CONSTRAINT entry_exactly_one_unit",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name='assetversionentry',
                    constraint=models.CheckConstraint(condition=models.Q(models.Q(('ayah__isnull', True), ('page_no__isnull', True), ('sura__isnull', False), ('word__isnull', True)), models.Q(('ayah__isnull', False), ('page_no__isnull', True), ('sura__isnull', True), ('word__isnull', True)), models.Q(('ayah__isnull', True), ('page_no__isnull', True), ('sura__isnull', True), ('word__isnull', False)), models.Q(('ayah__isnull', True), ('page_no__isnull', False), ('sura__isnull', True), ('word__isnull', True)), _connector='OR'), name='entry_exactly_one_unit'),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='assetversionentry',
            constraint=models.UniqueConstraint(fields=('version', 'sura'), name='unique_entry_per_version_sura'),
        ),
        migrations.AddConstraint(
            model_name='assetversionentry',
            constraint=models.UniqueConstraint(fields=('version', 'word'), name='unique_entry_per_version_word'),
        ),
        migrations.AddConstraint(
            model_name='assetversionentry',
            constraint=models.UniqueConstraint(fields=('version', 'page_no'), name='unique_entry_per_version_page'),
        ),
    ]
