# Generated by Django 5.2.14 on 2026-10-04 15:16

import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def backfill_published_version(apps: Apps, schema_editor: BaseDatabaseSchemaEditor | None) -> None:
    """Pin every translation / tafsir language to the version consumers see today.

    Until now consumers were served the newest committed version (newest-wins), so
    pointing each language at that same version keeps what consumers see unchanged
    on deploy. Mirrors ``Asset.get_latest_version`` exactly.
    """
    AssetLanguage = apps.get_model("content", "AssetLanguage")
    AssetVersion = apps.get_model("content", "AssetVersion")
    renditions = AssetLanguage.objects.filter(asset__category__in=["translation", "tafsir"])
    for rendition in renditions.iterator():
        newest = (
            AssetVersion.objects.filter(
                asset_id=rendition.asset_id,
                state="published",
                asset_language__language=rendition.language,
            )
            .order_by("-created_at")
            .first()
        )
        if newest is not None:
            rendition.published_version = newest
            rendition.save(update_fields=["published_version"])


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0068_seed_mushaf_layouts"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetlanguage",
            name="published_version",
            field=models.ForeignKey(
                blank=True,
                help_text="The version consumers are served for this language (translations / tafsirs). Set only by publishing a fully approved version; empty means nothing is visible.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="content.assetversion",
            ),
        ),
        migrations.RunPython(backfill_published_version, migrations.RunPython.noop),
    ]
