# Generated by Django 5.2.14 on 2026-10-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0069_assetlanguage_published_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetversion",
            name="label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Human-readable version name (tafsirs and translations).",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="assetversion",
            name="name",
            field=models.CharField(
                help_text="Asset version name. For tafsirs and translations this is the version number ('major.minor'), issued by the server and immutable; blank on drafts.",
                max_length=255,
            ),
        ),
    ]
