# Generated by Django 5.2.14 on 2026-10-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0071_number_tafsir_translation_versions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Distribution',
        ),
    ]
