import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// sidebar.ts is generated by `npx docusaurus gen-api-docs public` and is
// gitignored. The try/catch handles the case where gen-api-docs hasn't been
// run yet (fresh clone, before CI generation step).
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let publicApiSidebar: any[] = [];
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  publicApiSidebar = (require('./docs/reference/api/sidebar').default ?? [])
    // Drop the generated OpenAPI "Introduction" info page — its content is
    // already covered by the API Reference overview (reference/api/index).
    .filter((item: any) => item.id !== 'reference/api/itqan-cms-public-apis');
} catch {
  // not yet generated — run: npx docusaurus gen-api-docs public
}

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/quickstart',
        'getting-started/authentication',
      ],
    },
    {
      type: 'category',
      label: 'API Guides',
      collapsed: false,
      items: [
        'guides/api-design',
        'guides/response-structure',
        'guides/pagination',
        'guides/localization',
        'guides/related-resources',
        'guides/recitations-ayah-timings',
        'guides/search-filter-order',
        'guides/errors',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'doc', id: 'reference/api/index'},
      items: publicApiSidebar,
    },
  ],
};

export default sidebars;
