# Generated by Django 5.2.13 on 2026-05-07 11:28

from django.db import migrations, models
import ninja_keys.validators


class Migration(migrations.Migration):

    dependencies = [
        ("ninja_keys", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="expiry_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Once API key expires, users cannot use it anymore.",
                null=True,
                validators=[ninja_keys.validators.validate_timezone_aware],
                verbose_name="Expires",
            ),
        ),
    ]
