# Generated by Django 4.2.23 on 2025-08-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="description_ar",
            field=models.TextField(
                help_text="Detailed description of the resource content", null=True
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="description_en",
            field=models.TextField(
                help_text="Detailed description of the resource content", null=True
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="title_ar",
            field=models.CharField(
                help_text="Title of the Quranic resource", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="title_en",
            field=models.CharField(
                help_text="Title of the Quranic resource", max_length=255, null=True
            ),
        ),
    ]
