# Generated by Django 4.2.23 on 2025-09-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        # First, drop the existing license table (it has old structure from licensing app)
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS license CASCADE;",
            reverse_sql="-- Cannot reverse license table drop"
        ),
        
        # Create new license table with proper structure
        migrations.RunSQL(
            sql="""
            CREATE TABLE license (
                id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                created_at timestamp with time zone NOT NULL,
                updated_at timestamp with time zone NOT NULL,
                is_active boolean NOT NULL DEFAULT true,
                code varchar(50) NOT NULL UNIQUE,
                name varchar(255) NOT NULL,
                name_en varchar(255),
                name_ar varchar(255),
                short_name varchar(50) NOT NULL DEFAULT '',
                url varchar(200) NOT NULL DEFAULT '',
                icon_url varchar(200) NOT NULL DEFAULT '',
                summary text NOT NULL DEFAULT '',
                summary_en text,
                summary_ar text,
                full_text text NOT NULL DEFAULT '',
                full_text_en text,
                full_text_ar text,
                legal_code_url varchar(200) NOT NULL DEFAULT '',
                license_terms jsonb NOT NULL DEFAULT '[]',
                permissions jsonb NOT NULL DEFAULT '[]',
                conditions jsonb NOT NULL DEFAULT '[]',
                limitations jsonb NOT NULL DEFAULT '[]',
                is_default boolean NOT NULL DEFAULT false
            );
            
            -- Create indexes
            CREATE INDEX idx_license_code ON license (code);
            CREATE INDEX idx_license_is_default ON license (is_default);
            CREATE INDEX idx_license_is_active ON license (is_active);
            """,
            reverse_sql="DROP TABLE IF EXISTS license;"
        ),
    ]
