# Generated by Django 4.2.23 on 2025-09-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceversion',
            name='size_bytes',
            field=models.PositiveBigIntegerField(default=0, help_text='File size in bytes'),
        ),
    ]
