# Generated by Django 4.2.24 on 2025-09-15 15:06

import apps.core.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_alter_resourceversion_size_bytes"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Snapshot title displayed in UI", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional snapshot description"
                    ),
                ),
                (
                    "snapshot",
                    models.ImageField(
                        blank=True,
                        help_text="Snapshot image",
                        upload_to=apps.core.utils.upload_to_asset_snapshot_images,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"]
                            )
                        ],
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, help_text="Display order"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether snapshot is visible"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="content.asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Snapshot",
                "verbose_name_plural": "Asset Snapshots",
                "db_table": "asset_snapshot",
                "ordering": ["order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["asset"], name="asset_snaps_asset_i_3ecca1_idx"
                    ),
                    models.Index(fields=["order"], name="asset_snaps_order_d8ed28_idx"),
                    models.Index(
                        fields=["is_active"], name="asset_snaps_is_acti_7bd646_idx"
                    ),
                ],
            },
        ),
    ]
