# Generated by Django 4.2.23 on 2025-09-04 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_transform_license_table'),
    ]

    operations = [
        # This migration should only add missing columns/fields to existing tables
        # For fresh installations, 0001_initial already creates the correct structure
        # For existing installations, we only need to add missing fields
        
        # Add missing columns to resource table if they don't exist
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                -- Add 'status' column if it doesn't exist
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'resource' 
                    AND column_name = 'status' 
                    AND table_schema = 'public'
                ) THEN
                    ALTER TABLE resource ADD COLUMN status varchar(20) NOT NULL DEFAULT 'draft';
                    CREATE INDEX IF NOT EXISTS idx_resource_status ON resource (status);
                    RAISE NOTICE 'Added status column to resource table';
                ELSE
                    RAISE NOTICE 'Status column already exists in resource table';
                END IF;
            END $$;
            """,
            reverse_sql="ALTER TABLE resource DROP COLUMN IF EXISTS status;"
        ),
        
        # Ensure all required indexes exist on resource table
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS idx_resource_publishing_organization ON resource (publishing_organization_id);
            CREATE INDEX IF NOT EXISTS idx_resource_category ON resource (category);
            CREATE INDEX IF NOT EXISTS idx_resource_slug ON resource (slug);
            CREATE INDEX IF NOT EXISTS idx_resource_is_active ON resource (is_active);
            """,
            reverse_sql="-- Index cleanup not needed"
        ),
    ]
