# Generated by Django 4.2.23 on 2025-09-04 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_transform_resource_and_add_resource_version'),
    ]

    operations = [
        # Create Asset table
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS asset (
                id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                created_at timestamp with time zone NOT NULL,
                updated_at timestamp with time zone NOT NULL,
                is_active boolean NOT NULL DEFAULT true,
                name varchar(255) NOT NULL,
                title varchar(255) NOT NULL,
                title_en varchar(255),
                title_ar varchar(255),
                description text NOT NULL,
                description_en text,
                description_ar text,
                long_description text NOT NULL DEFAULT '',
                long_description_en text,
                long_description_ar text,
                thumbnail_url varchar(200) NOT NULL DEFAULT '',
                category varchar(20) NOT NULL,
                file_size varchar(50) NOT NULL,
                format varchar(50) NOT NULL,
                encoding varchar(50) NOT NULL DEFAULT 'UTF-8',
                version varchar(50) NOT NULL,
                language varchar(10) NOT NULL,
                download_count integer NOT NULL DEFAULT 0 CHECK (download_count >= 0),
                view_count integer NOT NULL DEFAULT 0 CHECK (view_count >= 0),
                license_id integer NOT NULL,
                publishing_organization_id integer NOT NULL,
                FOREIGN KEY (license_id) REFERENCES license(id) ON DELETE RESTRICT,
                FOREIGN KEY (publishing_organization_id) REFERENCES publishing_organization(id) ON DELETE RESTRICT
            );
            
            -- Create indexes for asset table
            CREATE INDEX IF NOT EXISTS idx_asset_publishing_organization ON asset (publishing_organization_id);
            CREATE INDEX IF NOT EXISTS idx_asset_category ON asset (category);
            CREATE INDEX IF NOT EXISTS idx_asset_license ON asset (license_id);
            CREATE INDEX IF NOT EXISTS idx_asset_is_active ON asset (is_active);
            """,
            reverse_sql="DROP TABLE IF EXISTS asset;"
        ),
        
        # Create AssetVersion table
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS asset_version (
                id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                created_at timestamp with time zone NOT NULL,
                updated_at timestamp with time zone NOT NULL,
                is_active boolean NOT NULL DEFAULT true,
                name varchar(255) NOT NULL,
                summary text NOT NULL DEFAULT '',
                file_url varchar(200) NOT NULL,
                size_bytes bigint NOT NULL DEFAULT 0 CHECK (size_bytes >= 0),
                asset_id integer NOT NULL,
                resource_version_id integer NOT NULL,
                FOREIGN KEY (asset_id) REFERENCES asset(id) ON DELETE CASCADE,
                FOREIGN KEY (resource_version_id) REFERENCES resource_version(id) ON DELETE CASCADE
            );
            
            -- Create indexes for asset_version table
            CREATE INDEX IF NOT EXISTS idx_asset_version_asset ON asset_version (asset_id);
            CREATE INDEX IF NOT EXISTS idx_asset_version_resource_version ON asset_version (resource_version_id);
            CREATE INDEX IF NOT EXISTS idx_asset_version_is_active ON asset_version (is_active);
            """,
            reverse_sql="DROP TABLE IF EXISTS asset_version;"
        ),
    ]
