# Generated by Django 4.2.23 on 2025-09-04 13:40

import apps.core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0008_convert_url_fields_to_file_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="thumbnail_image",
        ),
        migrations.RemoveField(
            model_name="assetversion",
            name="file",
        ),
        migrations.RemoveField(
            model_name="license",
            name="icon_image",
        ),
        migrations.RemoveField(
            model_name="publishingorganization",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="publishingorganization",
            name="icon_image",
        ),
        migrations.RemoveField(
            model_name="resourceversion",
            name="file",
        ),
        migrations.AddField(
            model_name="asset",
            name="thumbnail_url",
            field=models.ImageField(
                blank=True,
                help_text="Asset thumbnail image",
                upload_to=apps.core.utils.upload_to_asset_thumbnails,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="assetversion",
            name="file_url",
            field=models.FileField(
                blank=True,
                help_text="Direct file for asset",
                null=True,
                upload_to=apps.core.utils.upload_to_asset_files,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "doc",
                            "docx",
                            "txt",
                            "zip",
                            "tar",
                            "gz",
                            "json",
                            "xml",
                            "csv",
                        ]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="icon_url",
            field=models.ImageField(
                blank=True,
                help_text="License icon image",
                upload_to=apps.core.utils.upload_to_license_icons,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif", "webp", "svg"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="publishingorganization",
            name="cover_url",
            field=models.ImageField(
                blank=True,
                help_text="Cover image for organization",
                upload_to=apps.core.utils.upload_to_organization_covers,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="publishingorganization",
            name="icone_image_url",
            field=models.ImageField(
                blank=True,
                help_text="Icon/logo image - used in V1 UI: Publisher Page",
                upload_to=apps.core.utils.upload_to_organization_icons,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif", "webp", "svg"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="resourceversion",
            name="storage_url",
            field=models.FileField(
                blank=True,
                help_text="File storage for resource version",
                null=True,
                upload_to=apps.core.utils.upload_to_resource_files,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "doc",
                            "docx",
                            "txt",
                            "zip",
                            "tar",
                            "gz",
                            "json",
                            "xml",
                            "csv",
                        ]
                    )
                ],
            ),
        ),
    ]
