# Generated by Django 5.1.12 on 2025-09-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, verbose_name="Bio"),
        ),
        migrations.AddField(
            model_name="user",
            name="work_summary",
            field=models.TextField(blank=True, verbose_name="Work Summary"),
        ),
    ]
