# Generated by Django 5.2.6 on 2025-09-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="developer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when this record was created"
            ),
        ),
    ]
