# Generated by Django 5.2.6 on 2025-11-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_developer_created_at_alter_user_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="developer",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
