version: '3.9'

services:
  web:
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile.backend
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.staging
      PYTHONUNBUFFERED: "1"
      PGSSLMODE: require
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ../../src:/app:rw
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    restart: unless-stopped
    depends_on:
      - caddy

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      SITE_DOMAIN: ${SITE_DOMAIN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - static_volume:/srv/static:ro
      - media_volume:/srv/media:ro
      - caddy_logs:/var/log/caddy
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
  caddy_data:
  caddy_config:
  caddy_logs:
