# Generated by Django 4.2.23 on 2025-09-04 09:42

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_drop_account_emailaddress'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        # Skip removing is_deleted field if it doesn't exist - Role model already inherits is_active from BaseModel
        # migrations.RemoveField(
        #     model_name='role',
        #     name='is_deleted',
        # ),
        # migrations.AddField(
        #     model_name='role',
        #     name='is_active',
        #     field=models.BooleanField(default=True, help_text='Whether this record is active (soft delete mechanism)'),
        # ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.AutoField(help_text='Unique identifier for this record', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(help_text='Unique identifier for this user', primary_key=True, serialize=False),
        ),
    ]
