# Generated by Django 4.2.23 on 2025-09-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers_remove_role_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this record is active (soft delete mechanism)'),
        ),
    ]
