# Generated by Django 4.2.23 on 2025-09-04 13:41

import apps.core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_convert_avatar_url_to_image_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar_image",
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.ImageField(
                blank=True,
                help_text="User's avatar image",
                upload_to=apps.core.utils.upload_to_user_avatars,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"]
                    )
                ],
            ),
        ),
    ]
