from typing import Any

# Quran surah info extracted from trusted source qul.tarteel.ai (https://qul.tarteel.ai/resources/quran-metadata/70)
# To be considered into Lubb ecosystem
QURAN_SURAHS: dict[int, dict[str, Any]] = {
    1: {
        "name": "الفاتحة",
        "name_en": "Al-Fatihah",
        "revelation_order": 5,
        "revelation_place": "Makkah",
        "ayahs_count": 7,
    },
    2: {
        "name": "البقرة",
        "name_en": "Al-Baqarah",
        "revelation_order": 87,
        "revelation_place": "Madinah",
        "ayahs_count": 286,
    },
    3: {
        "name": "آل عمران",
        "name_en": "Ali 'Imran",
        "revelation_order": 89,
        "revelation_place": "Madinah",
        "ayahs_count": 200,
    },
    4: {
        "name": "النساء",
        "name_en": "An-Nisa",
        "revelation_order": 92,
        "revelation_place": "Madinah",
        "ayahs_count": 176,
    },
    5: {
        "name": "المائدة",
        "name_en": "Al-Ma'idah",
        "revelation_order": 112,
        "revelation_place": "Madinah",
        "ayahs_count": 120,
    },
    6: {
        "name": "الأنعام",
        "name_en": "Al-An'am",
        "revelation_order": 55,
        "revelation_place": "Makkah",
        "ayahs_count": 165,
    },
    7: {
        "name": "الأعراف",
        "name_en": "Al-A'raf",
        "revelation_order": 39,
        "revelation_place": "Makkah",
        "ayahs_count": 206,
    },
    8: {
        "name": "الأنفال",
        "name_en": "Al-Anfal",
        "revelation_order": 88,
        "revelation_place": "Madinah",
        "ayahs_count": 75,
    },
    9: {
        "name": "التوبة",
        "name_en": "At-Tawbah",
        "revelation_order": 113,
        "revelation_place": "Madinah",
        "ayahs_count": 129,
    },
    10: {
        "name": "يونس",
        "name_en": "Yunus",
        "revelation_order": 51,
        "revelation_place": "Makkah",
        "ayahs_count": 109,
    },
    11: {
        "name": "هود",
        "name_en": "Hud",
        "revelation_order": 52,
        "revelation_place": "Makkah",
        "ayahs_count": 123,
    },
    12: {
        "name": "يوسف",
        "name_en": "Yusuf",
        "revelation_order": 53,
        "revelation_place": "Makkah",
        "ayahs_count": 111,
    },
    13: {
        "name": "الرعد",
        "name_en": "Ar-Ra'd",
        "revelation_order": 96,
        "revelation_place": "Madinah",
        "ayahs_count": 43,
    },
    14: {
        "name": "ابراهيم",
        "name_en": "Ibrahim",
        "revelation_order": 72,
        "revelation_place": "Makkah",
        "ayahs_count": 52,
    },
    15: {
        "name": "الحجر",
        "name_en": "Al-Hijr",
        "revelation_order": 54,
        "revelation_place": "Makkah",
        "ayahs_count": 99,
    },
    16: {
        "name": "النحل",
        "name_en": "An-Nahl",
        "revelation_order": 70,
        "revelation_place": "Makkah",
        "ayahs_count": 128,
    },
    17: {
        "name": "الإسراء",
        "name_en": "Al-Isra",
        "revelation_order": 50,
        "revelation_place": "Makkah",
        "ayahs_count": 111,
    },
    18: {
        "name": "الكهف",
        "name_en": "Al-Kahf",
        "revelation_order": 69,
        "revelation_place": "Makkah",
        "ayahs_count": 110,
    },
    19: {
        "name": "مريم",
        "name_en": "Maryam",
        "revelation_order": 44,
        "revelation_place": "Makkah",
        "ayahs_count": 98,
    },
    20: {
        "name": "طه",
        "name_en": "Taha",
        "revelation_order": 45,
        "revelation_place": "Makkah",
        "ayahs_count": 135,
    },
    21: {
        "name": "الأنبياء",
        "name_en": "Al-Anbya",
        "revelation_order": 73,
        "revelation_place": "Makkah",
        "ayahs_count": 112,
    },
    22: {
        "name": "الحج",
        "name_en": "Al-Hajj",
        "revelation_order": 103,
        "revelation_place": "Madinah",
        "ayahs_count": 78,
    },
    23: {
        "name": "المؤمنون",
        "name_en": "Al-Mu'minun",
        "revelation_order": 74,
        "revelation_place": "Makkah",
        "ayahs_count": 118,
    },
    24: {
        "name": "النور",
        "name_en": "An-Nur",
        "revelation_order": 102,
        "revelation_place": "Madinah",
        "ayahs_count": 64,
    },
    25: {
        "name": "الفرقان",
        "name_en": "Al-Furqan",
        "revelation_order": 42,
        "revelation_place": "Makkah",
        "ayahs_count": 77,
    },
    26: {
        "name": "الشعراء",
        "name_en": "Ash-Shu'ara",
        "revelation_order": 47,
        "revelation_place": "Makkah",
        "ayahs_count": 227,
    },
    27: {
        "name": "النمل",
        "name_en": "An-Naml",
        "revelation_order": 48,
        "revelation_place": "Makkah",
        "ayahs_count": 93,
    },
    28: {
        "name": "القصص",
        "name_en": "Al-Qasas",
        "revelation_order": 49,
        "revelation_place": "Makkah",
        "ayahs_count": 88,
    },
    29: {
        "name": "العنكبوت",
        "name_en": "Al-'Ankabut",
        "revelation_order": 85,
        "revelation_place": "Makkah",
        "ayahs_count": 69,
    },
    30: {
        "name": "الروم",
        "name_en": "Ar-Rum",
        "revelation_order": 84,
        "revelation_place": "Makkah",
        "ayahs_count": 60,
    },
    31: {
        "name": "لقمان",
        "name_en": "Luqman",
        "revelation_order": 57,
        "revelation_place": "Makkah",
        "ayahs_count": 34,
    },
    32: {
        "name": "السجدة",
        "name_en": "As-Sajdah",
        "revelation_order": 75,
        "revelation_place": "Makkah",
        "ayahs_count": 30,
    },
    33: {
        "name": "الأحزاب",
        "name_en": "Al-Ahzab",
        "revelation_order": 90,
        "revelation_place": "Madinah",
        "ayahs_count": 73,
    },
    34: {
        "name": "سبإ",
        "name_en": "Saba",
        "revelation_order": 58,
        "revelation_place": "Makkah",
        "ayahs_count": 54,
    },
    35: {
        "name": "فاطر",
        "name_en": "Fatir",
        "revelation_order": 43,
        "revelation_place": "Makkah",
        "ayahs_count": 45,
    },
    36: {
        "name": "يس",
        "name_en": "Ya-Sin",
        "revelation_order": 41,
        "revelation_place": "Makkah",
        "ayahs_count": 83,
    },
    37: {
        "name": "الصافات",
        "name_en": "As-Saffat",
        "revelation_order": 56,
        "revelation_place": "Makkah",
        "ayahs_count": 182,
    },
    38: {
        "name": "ص",
        "name_en": "Sad",
        "revelation_order": 38,
        "revelation_place": "Makkah",
        "ayahs_count": 88,
    },
    39: {
        "name": "الزمر",
        "name_en": "Az-Zumar",
        "revelation_order": 59,
        "revelation_place": "Makkah",
        "ayahs_count": 75,
    },
    40: {
        "name": "غافر",
        "name_en": "Ghafir",
        "revelation_order": 60,
        "revelation_place": "Makkah",
        "ayahs_count": 85,
    },
    41: {
        "name": "فصلت",
        "name_en": "Fussilat",
        "revelation_order": 61,
        "revelation_place": "Makkah",
        "ayahs_count": 54,
    },
    42: {
        "name": "الشورى",
        "name_en": "Ash-Shuraa",
        "revelation_order": 62,
        "revelation_place": "Makkah",
        "ayahs_count": 53,
    },
    43: {
        "name": "الزخرف",
        "name_en": "Az-Zukhruf",
        "revelation_order": 63,
        "revelation_place": "Makkah",
        "ayahs_count": 89,
    },
    44: {
        "name": "الدخان",
        "name_en": "Ad-Dukhan",
        "revelation_order": 64,
        "revelation_place": "Makkah",
        "ayahs_count": 59,
    },
    45: {
        "name": "الجاثية",
        "name_en": "Al-Jathiyah",
        "revelation_order": 65,
        "revelation_place": "Makkah",
        "ayahs_count": 37,
    },
    46: {
        "name": "الأحقاف",
        "name_en": "Al-Ahqaf",
        "revelation_order": 66,
        "revelation_place": "Makkah",
        "ayahs_count": 35,
    },
    47: {
        "name": "محمد",
        "name_en": "Muhammad",
        "revelation_order": 95,
        "revelation_place": "Madinah",
        "ayahs_count": 38,
    },
    48: {
        "name": "الفتح",
        "name_en": "Al-Fath",
        "revelation_order": 111,
        "revelation_place": "Madinah",
        "ayahs_count": 29,
    },
    49: {
        "name": "الحجرات",
        "name_en": "Al-Hujurat",
        "revelation_order": 106,
        "revelation_place": "Madinah",
        "ayahs_count": 18,
    },
    50: {
        "name": "ق",
        "name_en": "Qaf",
        "revelation_order": 34,
        "revelation_place": "Makkah",
        "ayahs_count": 45,
    },
    51: {
        "name": "الذاريات",
        "name_en": "Adh-Dhariyat",
        "revelation_order": 67,
        "revelation_place": "Makkah",
        "ayahs_count": 60,
    },
    52: {
        "name": "الطور",
        "name_en": "At-Tur",
        "revelation_order": 76,
        "revelation_place": "Makkah",
        "ayahs_count": 49,
    },
    53: {
        "name": "النجم",
        "name_en": "An-Najm",
        "revelation_order": 23,
        "revelation_place": "Makkah",
        "ayahs_count": 62,
    },
    54: {
        "name": "القمر",
        "name_en": "Al-Qamar",
        "revelation_order": 37,
        "revelation_place": "Makkah",
        "ayahs_count": 55,
    },
    55: {
        "name": "الرحمن",
        "name_en": "Ar-Rahman",
        "revelation_order": 97,
        "revelation_place": "Madinah",
        "ayahs_count": 78,
    },
    56: {
        "name": "الواقعة",
        "name_en": "Al-Waqi'ah",
        "revelation_order": 46,
        "revelation_place": "Makkah",
        "ayahs_count": 96,
    },
    57: {
        "name": "الحديد",
        "name_en": "Al-Hadid",
        "revelation_order": 94,
        "revelation_place": "Madinah",
        "ayahs_count": 29,
    },
    58: {
        "name": "المجادلة",
        "name_en": "Al-Mujadila",
        "revelation_order": 105,
        "revelation_place": "Madinah",
        "ayahs_count": 22,
    },
    59: {
        "name": "الحشر",
        "name_en": "Al-Hashr",
        "revelation_order": 101,
        "revelation_place": "Madinah",
        "ayahs_count": 24,
    },
    60: {
        "name": "الممتحنة",
        "name_en": "Al-Mumtahanah",
        "revelation_order": 91,
        "revelation_place": "Madinah",
        "ayahs_count": 13,
    },
    61: {
        "name": "الصف",
        "name_en": "As-Saf",
        "revelation_order": 109,
        "revelation_place": "Madinah",
        "ayahs_count": 14,
    },
    62: {
        "name": "الجمعة",
        "name_en": "Al-Jumu'ah",
        "revelation_order": 110,
        "revelation_place": "Madinah",
        "ayahs_count": 11,
    },
    63: {
        "name": "المنافقون",
        "name_en": "Al-Munafiqun",
        "revelation_order": 104,
        "revelation_place": "Madinah",
        "ayahs_count": 11,
    },
    64: {
        "name": "التغابن",
        "name_en": "At-Taghabun",
        "revelation_order": 108,
        "revelation_place": "Madinah",
        "ayahs_count": 18,
    },
    65: {
        "name": "الطلاق",
        "name_en": "At-Talaq",
        "revelation_order": 99,
        "revelation_place": "Madinah",
        "ayahs_count": 12,
    },
    66: {
        "name": "التحريم",
        "name_en": "At-Tahrim",
        "revelation_order": 107,
        "revelation_place": "Madinah",
        "ayahs_count": 12,
    },
    67: {
        "name": "الملك",
        "name_en": "Al-Mulk",
        "revelation_order": 77,
        "revelation_place": "Makkah",
        "ayahs_count": 30,
    },
    68: {
        "name": "القلم",
        "name_en": "Al-Qalam",
        "revelation_order": 2,
        "revelation_place": "Makkah",
        "ayahs_count": 52,
    },
    69: {
        "name": "الحاقة",
        "name_en": "Al-Haqqah",
        "revelation_order": 78,
        "revelation_place": "Makkah",
        "ayahs_count": 52,
    },
    70: {
        "name": "المعارج",
        "name_en": "Al-Ma'arij",
        "revelation_order": 79,
        "revelation_place": "Makkah",
        "ayahs_count": 44,
    },
    71: {
        "name": "نوح",
        "name_en": "Nuh",
        "revelation_order": 71,
        "revelation_place": "Makkah",
        "ayahs_count": 28,
    },
    72: {
        "name": "الجن",
        "name_en": "Al-Jinn",
        "revelation_order": 40,
        "revelation_place": "Makkah",
        "ayahs_count": 28,
    },
    73: {
        "name": "المزمل",
        "name_en": "Al-Muzzammil",
        "revelation_order": 3,
        "revelation_place": "Makkah",
        "ayahs_count": 20,
    },
    74: {
        "name": "المدثر",
        "name_en": "Al-Muddaththir",
        "revelation_order": 4,
        "revelation_place": "Makkah",
        "ayahs_count": 56,
    },
    75: {
        "name": "القيامة",
        "name_en": "Al-Qiyamah",
        "revelation_order": 31,
        "revelation_place": "Makkah",
        "ayahs_count": 40,
    },
    76: {
        "name": "الانسان",
        "name_en": "Al-Insan",
        "revelation_order": 98,
        "revelation_place": "Madinah",
        "ayahs_count": 31,
    },
    77: {
        "name": "المرسلات",
        "name_en": "Al-Mursalat",
        "revelation_order": 33,
        "revelation_place": "Makkah",
        "ayahs_count": 50,
    },
    78: {
        "name": "النبإ",
        "name_en": "An-Naba",
        "revelation_order": 80,
        "revelation_place": "Makkah",
        "ayahs_count": 40,
    },
    79: {
        "name": "النازعات",
        "name_en": "An-Nazi'at",
        "revelation_order": 81,
        "revelation_place": "Makkah",
        "ayahs_count": 46,
    },
    80: {
        "name": "عبس",
        "name_en": "'Abasa",
        "revelation_order": 24,
        "revelation_place": "Makkah",
        "ayahs_count": 42,
    },
    81: {
        "name": "التكوير",
        "name_en": "At-Takwir",
        "revelation_order": 7,
        "revelation_place": "Makkah",
        "ayahs_count": 29,
    },
    82: {
        "name": "الإنفطار",
        "name_en": "Al-Infitar",
        "revelation_order": 82,
        "revelation_place": "Makkah",
        "ayahs_count": 19,
    },
    83: {
        "name": "المطففين",
        "name_en": "Al-Mutaffifin",
        "revelation_order": 86,
        "revelation_place": "Makkah",
        "ayahs_count": 36,
    },
    84: {
        "name": "الإنشقاق",
        "name_en": "Al-Inshiqaq",
        "revelation_order": 83,
        "revelation_place": "Makkah",
        "ayahs_count": 25,
    },
    85: {
        "name": "البروج",
        "name_en": "Al-Buruj",
        "revelation_order": 27,
        "revelation_place": "Makkah",
        "ayahs_count": 22,
    },
    86: {
        "name": "الطارق",
        "name_en": "At-Tariq",
        "revelation_order": 36,
        "revelation_place": "Makkah",
        "ayahs_count": 17,
    },
    87: {
        "name": "الأعلى",
        "name_en": "Al-A'la",
        "revelation_order": 8,
        "revelation_place": "Makkah",
        "ayahs_count": 19,
    },
    88: {
        "name": "الغاشية",
        "name_en": "Al-Ghashiyah",
        "revelation_order": 68,
        "revelation_place": "Makkah",
        "ayahs_count": 26,
    },
    89: {
        "name": "الفجر",
        "name_en": "Al-Fajr",
        "revelation_order": 10,
        "revelation_place": "Makkah",
        "ayahs_count": 30,
    },
    90: {
        "name": "البلد",
        "name_en": "Al-Balad",
        "revelation_order": 35,
        "revelation_place": "Makkah",
        "ayahs_count": 20,
    },
    91: {
        "name": "الشمس",
        "name_en": "Ash-Shams",
        "revelation_order": 26,
        "revelation_place": "Makkah",
        "ayahs_count": 15,
    },
    92: {
        "name": "الليل",
        "name_en": "Al-Layl",
        "revelation_order": 9,
        "revelation_place": "Makkah",
        "ayahs_count": 21,
    },
    93: {
        "name": "الضحى",
        "name_en": "Ad-Duhaa",
        "revelation_order": 11,
        "revelation_place": "Makkah",
        "ayahs_count": 11,
    },
    94: {
        "name": "الشرح",
        "name_en": "Ash-Sharh",
        "revelation_order": 12,
        "revelation_place": "Makkah",
        "ayahs_count": 8,
    },
    95: {
        "name": "التين",
        "name_en": "At-Tin",
        "revelation_order": 28,
        "revelation_place": "Makkah",
        "ayahs_count": 8,
    },
    96: {
        "name": "العلق",
        "name_en": "Al-'Alaq",
        "revelation_order": 1,
        "revelation_place": "Makkah",
        "ayahs_count": 19,
    },
    97: {
        "name": "القدر",
        "name_en": "Al-Qadr",
        "revelation_order": 25,
        "revelation_place": "Makkah",
        "ayahs_count": 5,
    },
    98: {
        "name": "البينة",
        "name_en": "Al-Bayyinah",
        "revelation_order": 100,
        "revelation_place": "Madinah",
        "ayahs_count": 8,
    },
    99: {
        "name": "الزلزلة",
        "name_en": "Az-Zalzalah",
        "revelation_order": 93,
        "revelation_place": "Madinah",
        "ayahs_count": 8,
    },
    100: {
        "name": "العاديات",
        "name_en": "Al-'Adiyat",
        "revelation_order": 14,
        "revelation_place": "Makkah",
        "ayahs_count": 11,
    },
    101: {
        "name": "القارعة",
        "name_en": "Al-Qari'ah",
        "revelation_order": 30,
        "revelation_place": "Makkah",
        "ayahs_count": 11,
    },
    102: {
        "name": "التكاثر",
        "name_en": "At-Takathur",
        "revelation_order": 16,
        "revelation_place": "Makkah",
        "ayahs_count": 8,
    },
    103: {
        "name": "العصر",
        "name_en": "Al-'Asr",
        "revelation_order": 13,
        "revelation_place": "Makkah",
        "ayahs_count": 3,
    },
    104: {
        "name": "الهمزة",
        "name_en": "Al-Humazah",
        "revelation_order": 32,
        "revelation_place": "Makkah",
        "ayahs_count": 9,
    },
    105: {
        "name": "الفيل",
        "name_en": "Al-Fil",
        "revelation_order": 19,
        "revelation_place": "Makkah",
        "ayahs_count": 5,
    },
    106: {
        "name": "قريش",
        "name_en": "Quraysh",
        "revelation_order": 29,
        "revelation_place": "Makkah",
        "ayahs_count": 4,
    },
    107: {
        "name": "الماعون",
        "name_en": "Al-Ma'un",
        "revelation_order": 17,
        "revelation_place": "Makkah",
        "ayahs_count": 7,
    },
    108: {
        "name": "الكوثر",
        "name_en": "Al-Kawthar",
        "revelation_order": 15,
        "revelation_place": "Makkah",
        "ayahs_count": 3,
    },
    109: {
        "name": "الكافرون",
        "name_en": "Al-Kafirun",
        "revelation_order": 18,
        "revelation_place": "Makkah",
        "ayahs_count": 6,
    },
    110: {
        "name": "النصر",
        "name_en": "An-Nasr",
        "revelation_order": 114,
        "revelation_place": "Madinah",
        "ayahs_count": 3,
    },
    111: {
        "name": "المسد",
        "name_en": "Al-Masad",
        "revelation_order": 6,
        "revelation_place": "Makkah",
        "ayahs_count": 5,
    },
    112: {
        "name": "الإخلاص",
        "name_en": "Al-Ikhlas",
        "revelation_order": 22,
        "revelation_place": "Makkah",
        "ayahs_count": 4,
    },
    113: {
        "name": "الفلق",
        "name_en": "Al-Falaq",
        "revelation_order": 20,
        "revelation_place": "Makkah",
        "ayahs_count": 5,
    },
    114: {
        "name": "الناس",
        "name_en": "An-Nas",
        "revelation_order": 21,
        "revelation_place": "Makkah",
        "ayahs_count": 6,
    },
}
