# Generated by Django 5.2.17 on 2026-09-06 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchedRepository",
            fields=[
                (
                    "id",
                    models.AutoField(help_text="Unique identifier for this record", primary_key=True, serialize=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when this record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when this record was last updated"),
                ),
                (
                    "host",
                    models.CharField(
                        choices=[("github", "GitHub")],
                        default="github",
                        help_text="Git host holding the repository. Only GitHub is supported in V1.",
                        max_length=32,
                    ),
                ),
                ("owner", models.CharField(help_text="Repository owner login (user or organization)", max_length=255)),
                (
                    "repository_name",
                    models.CharField(help_text="Repository name without the owner prefix", max_length=255),
                ),
                (
                    "installation_id",
                    models.BigIntegerField(
                        db_index=True, help_text="GitHub App installation ID that granted access to this repository"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("opted_in", "Opted in"), ("opted_out", "Opted out"), ("suspended", "Suspended")],
                        db_index=True,
                        default="opted_in",
                        help_text="Opt-in state. Only opted_in repositories are scanned for manifest updates.",
                        max_length=20,
                    ),
                ),
                (
                    "default_branch",
                    models.CharField(
                        default="main",
                        help_text="Branch manifest discovery reads when no explicit ref is given",
                        max_length=255,
                    ),
                ),
                (
                    "last_manifest_sha",
                    models.CharField(
                        blank=True,
                        help_text="Blob SHA of itqan-assets.yaml last seen by discovery (null = absent or never scanned)",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "last_lockfile_sha",
                    models.CharField(
                        blank=True,
                        help_text="Blob SHA of itqan-assets.lock last seen by discovery (null = absent or never scanned)",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When manifest discovery last scanned this repository (null = never scanned)",
                        null=True,
                    ),
                ),
                (
                    "opted_in_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the latest opt-in happened. Re-opt-in refreshes this timestamp.",
                    ),
                ),
                (
                    "opted_in_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff user who recorded the opt-in, if done through an authenticated surface.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependabot_opt_ins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["host", "status"], name="dependabot__host_d3d5de_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("host", "owner", "repository_name"), name="unique_watched_repository"
                    )
                ],
            },
        ),
    ]
