# Generated by Django 5.2.17 on 2026-09-06 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dependabot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchedrepository",
            name="default_branch",
            field=models.CharField(
                default="main",
                help_text="Initial branch guess. Discovery resolves the repository's real GitHub default branch and overwrites this.",
                max_length=255,
            ),
        ),
        migrations.AddConstraint(
            model_name="watchedrepository",
            constraint=models.CheckConstraint(
                condition=models.Q(("host", "github")), name="watched_repository_github_only"
            ),
        ),
    ]
