# Generated by Django 5.2.17 on 2026-09-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dependabot", "0002_alter_watchedrepository_default_branch_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.AutoField(help_text="Unique identifier for this record", primary_key=True, serialize=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when this record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when this record was last updated"),
                ),
                (
                    "delivery_id",
                    models.CharField(
                        help_text="X-GitHub-Delivery GUID. Unique per delivery, stable across redeliveries.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("event", models.CharField(help_text="X-GitHub-Event value of the delivery.", max_length=64)),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        help_text="Top-level payload action, if the event carries one.",
                        max_length=64,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
