# Generated by Django 4.2.23 on 2025-09-04 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyUsageEvent',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active (soft delete mechanism)')),
                ('event_type', models.CharField(choices=[('api_call', 'API Call'), ('download', 'Download'), ('view', 'View')], help_text='Type of usage event', max_length=20)),
                ('endpoint', models.CharField(help_text='Specific API endpoint or URL that was accessed', max_length=500)),
                ('request_size', models.PositiveIntegerField(default=0, help_text='Size of the request in bytes')),
                ('response_size', models.PositiveIntegerField(default=0, help_text='Size of the response in bytes')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the client making the request')),
                ('user_agent', models.TextField(help_text='User agent string from the client')),
                ('metadata', models.JSONField(default=dict, help_text='Additional event-specific metadata and tracking data')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the event occurred')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in the database')),
                ('distribution', models.ForeignKey(help_text='Specific distribution that was used', on_delete=django.db.models.deletion.CASCADE, related_name='legacy_usage_events', to='content.distribution')),
                ('resource', models.ForeignKey(help_text='Resource that was accessed', on_delete=django.db.models.deletion.CASCADE, related_name='legacy_usage_events', to='content.resource')),
                ('user', models.ForeignKey(help_text='User who triggered the event', on_delete=django.db.models.deletion.CASCADE, related_name='legacy_usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage Event',
                'verbose_name_plural': 'Usage Events',
                'db_table': 'legacy_usage_event',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['user'], name='legacy_usag_user_id_bf6810_idx'), models.Index(fields=['resource'], name='legacy_usag_resourc_dbe3be_idx'), models.Index(fields=['distribution'], name='legacy_usag_distrib_b233b0_idx'), models.Index(fields=['event_type'], name='legacy_usag_event_t_f17102_idx'), models.Index(fields=['occurred_at'], name='legacy_usag_occurre_fded4c_idx'), models.Index(fields=['ip_address'], name='legacy_usag_ip_addr_97a195_idx'), models.Index(fields=['user', 'occurred_at'], name='legacy_usag_user_id_6909e5_idx'), models.Index(fields=['resource', 'occurred_at'], name='legacy_usag_resourc_b3368d_idx'), models.Index(fields=['event_type', 'occurred_at'], name='legacy_usag_event_t_eb7078_idx')],
            },
        ),
    ]
