# Generated by Django 5.2.11 on 2026-03-09 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0027_add_bitrate_to_track"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.AutoField(help_text="Unique identifier for this record", primary_key=True, serialize=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when this record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when this record was last updated"),
                ),
                (
                    "preferred_reciter_ids",
                    models.JSONField(blank=True, default=list, help_text="List of preferred Reciter IDs"),
                ),
                (
                    "preferred_qiraah_ids",
                    models.JSONField(blank=True, default=list, help_text="List of preferred Qiraah IDs"),
                ),
                (
                    "preferred_riwayah_ids",
                    models.JSONField(blank=True, default=list, help_text="List of preferred Riwayah IDs"),
                ),
                (
                    "audio_quality",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        default="high",
                        help_text="Preferred audio quality",
                        max_length=10,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en", help_text="Preferred language code (e.g. 'en', 'ar')", max_length=10
                    ),
                ),
                (
                    "notification_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Notification preferences (e.g. {new_content: true, recommendations: true})",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User these preferences belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.AutoField(help_text="Unique identifier for this record", primary_key=True, serialize=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when this record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when this record was last updated"),
                ),
                (
                    "surah_number",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Surah number (1..114) if bookmarking a specific surah track", null=True
                    ),
                ),
                (
                    "position_ms",
                    models.PositiveIntegerField(help_text="Playback position in milliseconds for resume functionality"),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, default="", help_text="Optional user note for this bookmark (max 500 characters)"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset being bookmarked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="content.asset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this bookmark",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bookmark",
                "verbose_name_plural": "Bookmarks",
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="personaliza_user_id_df01df_idx"),
                    models.Index(fields=["user", "asset"], name="personaliza_user_id_0f60e9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.AutoField(help_text="Unique identifier for this record", primary_key=True, serialize=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when this record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when this record was last updated"),
                ),
                ("object_id", models.PositiveIntegerField(help_text="ID of the favorited content object")),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Django ContentType for the favorited object",
                        limit_choices_to={"model__in": ["reciter", "resource", "asset"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who favorited this item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorite",
                "verbose_name_plural": "Favorites",
                "indexes": [
                    models.Index(fields=["content_type", "object_id"], name="personaliza_content_095343_idx"),
                    models.Index(fields=["user", "created_at"], name="personaliza_user_id_61d482_idx"),
                ],
                "unique_together": {("user", "content_type", "object_id")},
            },
        ),
        migrations.CreateModel(
            name="ListeningHistory",
            fields=[
                (
                    "id",
                    models.AutoField(help_text="Unique identifier for this record", primary_key=True, serialize=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when this record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when this record was last updated"),
                ),
                (
                    "surah_number",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Surah number if listening to a specific surah track", null=True
                    ),
                ),
                (
                    "last_position_ms",
                    models.PositiveIntegerField(
                        default=0, help_text="Last playback position in milliseconds (for resume)"
                    ),
                ),
                (
                    "duration_listened_ms",
                    models.PositiveIntegerField(
                        default=0, help_text="Total duration listened in this session (milliseconds)"
                    ),
                ),
                ("played_at", models.DateTimeField(help_text="When the playback session occurred")),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset that was listened to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listening_history",
                        to="content.asset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who listened",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listening_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Listening History",
                "verbose_name_plural": "Listening History",
                "indexes": [models.Index(fields=["user", "-played_at"], name="personaliza_user_id_2cfd26_idx")],
                "unique_together": {("user", "asset", "surah_number")},
            },
        ),
    ]
