# Generated by Django 4.2.23 on 2025-08-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_yourself',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='business_model',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='team_size',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
