# Generated by Django 5.2.14 on 2026-06-18 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sura",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when this record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when this record was last updated"),
                ),
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        help_text="Canonical sura number (1-114)", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(help_text="Arabic name of the sura", max_length=64)),
                ("transliterated_name", models.CharField(help_text="Latin transliteration of the name", max_length=64)),
                ("english_name", models.CharField(help_text="English meaning of the name", max_length=128)),
                ("ayas_count", models.PositiveSmallIntegerField(help_text="Number of ayahs in this sura")),
                (
                    "start_offset",
                    models.PositiveSmallIntegerField(help_text="Cumulative number of ayahs in all preceding suras"),
                ),
                (
                    "revelation_type",
                    models.CharField(
                        choices=[("Meccan", "Meccan"), ("Medinan", "Medinan")],
                        help_text="Whether the sura was revealed in Mecca or Medina",
                        max_length=8,
                    ),
                ),
                (
                    "revelation_order",
                    models.PositiveSmallIntegerField(help_text="Order in which the sura was revealed"),
                ),
                ("rukus_count", models.PositiveSmallIntegerField(help_text="Number of rukus (sections) in this sura")),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Ayah",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when this record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when this record was last updated"),
                ),
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        help_text="Canonical global ayah index (1-6236)", primary_key=True, serialize=False
                    ),
                ),
                ("number_in_sura", models.PositiveSmallIntegerField(help_text="Ayah number within its sura (1-based)")),
                ("text", models.TextField(help_text="Uthmani text of the ayah")),
                ("juz", models.PositiveSmallIntegerField(help_text="Juz (part) number this ayah belongs to (1-30)")),
                (
                    "hizb_quarter",
                    models.PositiveSmallIntegerField(help_text="Hizb quarter number this ayah belongs to"),
                ),
                ("page", models.PositiveSmallIntegerField(help_text="Mushaf page number this ayah appears on")),
                (
                    "sura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ayahs", to="quran.sura"
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when this record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when this record was last updated"),
                ),
                (
                    "id",
                    models.PositiveIntegerField(
                        help_text="Canonical global word index", primary_key=True, serialize=False
                    ),
                ),
                (
                    "position_in_ayah",
                    models.PositiveSmallIntegerField(help_text="Word position within its ayah (1-based)"),
                ),
                ("text", models.CharField(help_text="The word text", max_length=128)),
                (
                    "ayah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="words", to="quran.ayah"
                    ),
                ),
                (
                    "sura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="words", to="quran.sura"
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="ayah",
            index=models.Index(fields=["sura", "number_in_sura"], name="quran_ayah_sura_id_f783bf_idx"),
        ),
        migrations.AddIndex(
            model_name="ayah",
            index=models.Index(fields=["page"], name="quran_ayah_page_0df5e7_idx"),
        ),
        migrations.AddConstraint(
            model_name="ayah",
            constraint=models.UniqueConstraint(fields=("sura", "number_in_sura"), name="unique_ayah_per_sura"),
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(fields=["ayah", "position_in_ayah"], name="quran_word_ayah_id_9f89a6_idx"),
        ),
    ]
