name: Debug Deploy

on:
  workflow_dispatch:  # Manual trigger for testing
  push:
    branches: [staging]  # Only test on staging first

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
      - name: Debug environment variables
        run: |
          echo "🔍 Debugging GitHub Actions Environment..."
          echo "Branch: ${GITHUB_REF_NAME}"
          echo "Repository: ${GITHUB_REPOSITORY}"
          echo "Actor: ${GITHUB_ACTOR}"
          
      - name: Check secrets availability  
        run: |
          echo "🔑 Checking secrets..."
          if [ -z "${{ secrets.STAGING_HOST }}" ]; then
            echo "❌ STAGING_HOST secret is missing or empty"
          else
            echo "✅ STAGING_HOST secret exists"
          fi
          
          if [ -z "${{ secrets.SSH_USER }}" ]; then
            echo "❌ SSH_USER secret is missing or empty"
          else
            echo "✅ SSH_USER secret exists"
          fi
          
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "❌ SSH_PRIVATE_KEY secret is missing or empty"
          else
            echo "✅ SSH_PRIVATE_KEY secret exists (length: ${#SSH_PRIVATE_KEY})"
          fi
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Test SSH connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🎉 SSH connection successful!"
            echo "🏠 Current directory: $(pwd)"
            echo "🗂️ Home directory contents:"
            ls -la ~
            echo "🐳 Docker status:"
            docker --version || echo "Docker not found"
            echo "📁 CMS directory check:"
            ls -la /srv/cms-backend || echo "CMS directory not found"
